import type { NgheData } from "./types";

export const JOB_03_THUONG: NgheData = {
  job: 3,
  tenNghe: "Thương",
  khiCong: [
    {
      index: 0,
      id: 30,
      ten: "Kim chung cương khí",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Tăng thẳng phòng ngự cơ bản, không qua %. Tối đa +80 phòng ngự ở 80 điểm.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case0 job3. Cộng thẳng vào tổng phòng ngự cơ bản (PlayersBes.cs:2087).",
    },
    {
      index: 1,
      id: 31,
      ten: "Vận khí liệu thương",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Tăng % lượng máu hồi phục nhận được từ mọi nguồn (thuốc, kỹ năng hồi máu, tự hồi). Đầu 80 điểm cộng thêm tới +90% lượng máu hồi mỗi lần.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs case1 job3: THUONG_VanKhi_LieuThuong = num2×heSo1+0.1. Tiêu thụ AddBlood() PlayersBes.cs~25355-25357, chỉ áp dụng Player_Job==3 — đúng đối tượng.",
    },
    {
      index: 2,
      id: 32,
      ten: "Liên hoàn phi vũ",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Đòn tay có cơ hội gây liên hoàn 2 nhát, nhân sát thương đòn đó lên khoảng x2. Giá trị field tối đa gốc 90 (10+80×1.0). Field này còn bị nhân dồn bởi khí công idx8 (Càn Khôn Na Di) — đã bị chặn về đúng trần 90 (xem DA_SUA ở idx8).",
      trangThai: "DA_SUA",
      ghiChu:
        "Players.cs ~40124-40136 (đòn tay PK, roll RNG.Next(1,100) — ĐÚNG). ĐÃ SỬA 03/09: đòn tay PvE (~40843) trước đây dùng RNG.Next(1,80) — cùng lỗi đã sửa cho Đao/Kiếm nhưng bị bỏ sót ở Thương, khiến ~70/80 điểm là proc 100%. Nay đổi thành RNG.Next(1,100) khớp đòn tay PK.",
    },
    {
      index: 3,
      id: 34,
      ten: "Cuồng phong vạn phá",
      loai: "goc",
      heSo1: 3000.0,
      heSo2: 0.02,
      batBuocThangThien: null,
      moTa: "Kéo dài thời gian trạng thái Nộ Khí Xung Thiên (gốc 10 giây, tối đa cộng thêm tới 240 giây ở 80 điểm).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case3 job3. Tiêu thụ Players.cs:69573. Field dùng chung 8 nghề, không riêng lỗi Thương.",
    },
    {
      index: 4,
      id: 35,
      ten: "Hoành luyện thái bảo",
      loai: "goc",
      heSo1: 8.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Tăng thẳng HP tối đa. Đầu 80 điểm cộng thêm tới 640 HP.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case4 job3. Cộng vào CharacterMax_HP (PlayersBes.cs:2124).",
    },
    {
      index: 5,
      id: 39,
      ten: "Chuyển công vi thủ",
      loai: "goc",
      heSo1: 0.45,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Khí công phòng thủ chỉ có tác dụng trong PK: khi bị đối phương đánh trúng (cả đòn tay lẫn chiêu), có cơ hội chuyển 1 phần sức công kích bản thân thành phòng ngự cho đòn đó. Đầu 80 điểm: ngưỡng proc và biên độ đều tối đa 41, tương đương +20.5% sức công kích thành phòng ngự.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case5 job3. Players.cs ~39668-39674 (đòn tay PK), ~44595-44599 (chiêu PK). Chỉ PK.",
    },
    {
      index: 6,
      id: 183,
      ten: "Khí trầm đan điền",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Buff nền tảng chung: cộng thêm HP và phòng ngự kỹ năng theo % phòng ngự cơ bản. Đầu 80 điểm cho tối đa 40% phòng ngự cơ bản.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case6 job3. Tiêu thụ chung PlayersBes.cs~8537-8542.",
    },
    {
      index: 7,
      id: 38,
      ten: "Cuồng thần hàng thế",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Hồi thêm Nộ Khí (SP) mỗi tick khi KHÔNG ở trạng thái Nộ Khí, tỉ lệ theo cấp độ nhân vật. Đầu 80 điểm cho hệ số tối đa 0.8.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case7 job3. Players.cs:48696-48706 (gate đúng job3 && !NoKhi).",
    },
    {
      index: 8,
      id: 36,
      ten: "Càn khôn na di",
      loai: "goc",
      heSo1: 0.015,
      heSo2: 0.15,
      batBuocThangThien: null,
      moTa:
        "Vừa tăng % sát thương chiêu (CLVC, tối đa +120% ở 80 điểm) vừa khuếch đại khí công Liên Hoàn Phi Vũ (idx2). 🔴 BUG NẶNG NHẤT toàn đợt audit: công thức gốc NHÂN THẲNG vào field của Liên Hoàn Phi Vũ khiến giá trị vọt lên tới 1170 (vượt trần gốc 90 gần 13 lần), khiến Liên Hoàn Phi Vũ luôn luôn nổ ở mọi đòn tay PvE lẫn PK chỉ với mức đầu tư nhẹ.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs case8 job3 (~7962-7971): base.THUONG_LienHoanPhiVu *= 1.0 + num2×heSo2, không trần, vọt tới 1170. ĐÃ SỬA: chặn if(THUONG_LienHoanPhiVu>90.0) = 90.0 ngay sau phép nhân. Xem thêm idx2 (bug RNG.Next(1,80) riêng còn tồn tại).",
    },
    {
      index: 9,
      id: 130,
      ten: "Mạt nhật cuồng vũ",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Khi bước vào Nộ Khí Xung Thiên, nhận thêm % tăng SONG SONG cả công lẫn thủ trong suốt thời gian rage. Gốc +25%, đầu 80 điểm cộng thêm tối đa +80%, tổng tối đa +105%.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case9 job3. Players.cs:69576-69583.",
    },
    {
      index: 10,
      id: 332,
      ten: "Nộ ý chi hống",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.2,
      batBuocThangThien: null,
      moTa: "Chỉ áp dụng cho CHIÊU: cơ hội (tối đa 80%) tăng sát thương chiêu thêm tối thiểu +20%; nếu đang Nộ Khí thì cộng thêm nhờ khí công Thăng Thiên 'Nộ ý chi hỏa' (lên tới +60%).",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs case10 job3. Players.cs:41293-41302 (PvE), 44950-44959 (PK). RỦI RO CHUNG đã biết (chưa sửa): skill hỗ trợ đồng đội VoCong_ID 401303 cộng THẲNG +10.0 vào field mỗi lần cast, không trần, không tự giảm khi buff hết hạn.",
    },
    {
      index: 11,
      id: 37,
      ten: "Linh giáp hộ thân",
      loai: "goc",
      heSo1: 0.008,
      heSo2: 3.0,
      batBuocThangThien: null,
      moTa: "Tăng thẳng lực phòng ngự võ công (kháng chiêu thức). Đầu 80 điểm cho tối đa 240 điểm ULPT.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs case11 job3 (~7978-7980), chỉ dùng hệ số2 (3.0) — hệ số1 (0.008) 'chết' nhưng đây là MẪU HÌNH NHẤT QUÁN (Cầm Sư case3, Quyền Sư case4 cũng vậy), không phải lỗi riêng.",
    },
    {
      index: null,
      id: 33,
      ten: "Thăng thiên 3 - Nộ ý chi hỏa",
      loai: "thang_thien",
      heSo1: 0.005,
      heSo2: null,
      batBuocThangThien: 8,
      moTa: "Không đứng độc lập — chỉ cộng thêm vào biên độ sát thương của Nộ Ý Chi Hống (idx10) khi đang Nộ Khí. Đầu 80 điểm cộng thêm tối đa +40% sát thương.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case33 (~8708-8710). Players.cs 41297-41300 (PvE), 44954-44957 (PK).",
    },
    {
      index: null,
      id: 330,
      ten: "Thăng thiên 1 - Phá giáp thứ hồn",
      loai: "thang_thien",
      heSo1: 1.0,
      heSo2: null,
      batBuocThangThien: 6,
      moTa: "Chỉ áp dụng cho chiêu loại hình 3 cấp≥5: cơ hội (tối đa 80% ở 80 điểm) cộng thêm sát thương chiêu bằng chính phòng ngự trang bị bản thân nhân hệ số 0.4.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case330 (~8702-8704). Players.cs 41277-41291 (PvE), 44935-44949 (PK).",
    },
    {
      index: null,
      id: 331,
      ten: "Thăng thiên 2 - Dĩ thối vi tiến",
      loai: "thang_thien",
      heSo1: 1.0,
      heSo2: null,
      batBuocThangThien: 7,
      moTa: "Chỉ kích hoạt khi đang Nộ Khí: cộng thêm cả tỉ lệ proc lẫn biên độ sát thương của Phá Giáp Thứ Hồn (id330). Đầu 80 điểm cộng thêm tối đa +80 ngưỡng và +0.8 hệ số.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs case331 (~8705-8707). Cùng vị trí với id330. Đầu dư cả 2 khí công có thể vượt roll 100 nhưng chỉ là 'luôn trúng', không khai thác thêm gì ngoài dự tính.",
    },
    {
      index: null,
      id: 333,
      ten: "Thăng thiên 4 - Hồng nguyệt cuồng phong",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Ultimate cấp cao (Level>=140, Thăng Thiên>=9): cơ hội (tối đa 40% ở 80 điểm) kích hoạt buff HP/MP tạm thời lan tới đồng đội.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case333 (~8711-8713), field dùng chung nhiều nghề. AscensionFourQigongTrigger Players.cs~46333.",
    },
    {
      index: null,
      id: 334,
      ten: "Thăng thiên 4 - Độc xà xuất động",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Cùng nhóm điều kiện id333: cơ hội gây debuff tạm thời 3s lên mục tiêu, khiến roll ngẫu nhiên khác của nạn nhân dễ 'ép' thành công trong 3s đó.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case334 (~8714-8716), field dùng chung. Trigger Players.cs~46095.",
    },
    {
      index: null,
      id: 572,
      ten: "Khí công bí cấp (Thăng Thiên 6 thức - Thương)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 11,
      moTa:
        "Ultimate Thăng Thiên 6 của Thương (field nội bộ 'HanBangLinhVuc'): khi ra chiêu có cơ hội (tối đa 8% ở 80 điểm) gửi hiệu ứng phụ trợ/khống chế nhóm (không gây sát thương) tới tối đa 6 đồng đội gần đó.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs case572 (~8875-8877). Players.cs ~41309-41313 (PvE), ~44965-44970 (PK). ĐÃ SỬA 03/09: ở PK-chiêu, điều kiện roll trước đây KHÔNG trừ Giam_Tac_dung_Cua_Khi_Cong (debuff Thần Nữ áp lên đối thủ) trong khi 3 khí công khác cùng khối if của Thương đều trừ đúng — nay đã bổ sung, nhất quán với nhóm.",
    },
    {
      index: null,
      id: 681,
      ten: "[Thương] Khí công bí cấp thư (Thăng Thiên 5 thức - Diệt Thế Cuồng Vũ)",
      loai: "thang_thien",
      heSo1: 0.3,
      heSo2: null,
      batBuocThangThien: 10,
      moTa:
        "Ultimate RIÊNG của Thương, không dùng chung field. Chỉ có thể proc khi KHÔNG đang Nộ Khí — một buff 'bù' sát thương cho pha combat thường (chưa/không rage). Đầu 80 điểm tỉ lệ proc tối đa 24%, khi trúng nhân sát thương chiêu thêm +20%.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs case681 (~8766-8768). Players.cs 41303-41307 (PvE), 44960-44964 (PK, trừ đúng Giam_Tac_dung_Cua_Khi_Cong — khác id572 bị thiếu ở trên).",
    },
  ],
};
