import type { NgheData } from "./types";

export const JOB_05_DAI_PHU: NgheData = {
  job: 5,
  tenNghe: "Đại Phu",
  khiCong: [
    {
      index: 0,
      id: 50,
      ten: "Vận khí hành tâm",
      loai: "goc",
      heSo1: 0.04,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Tăng tốc độ hồi MP tự nhiên: nhân hệ số (1+giá trị) vào lượng MP hồi mỗi tick, chỉ áp dụng job5. Trần ~70-80 điểm cho hệ số hồi MP lên tới +280%~320%.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case0 job5; tiêu thụ MagicPlus() PlayersBes.cs~25379-25381.",
    },
    {
      index: 1,
      id: 51,
      ten: "Thái cực tâm pháp",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Giảm % chi phí MP khi thi triển võ công (mức giảm = giá trị×0.01, tối đa 80%). Đây là 'mẫu chuẩn không vượt trần' dùng làm tham chiếu khi vá lỗi tương tự của Cầm Sư (CAMSU_CaoSonLuuThuy).",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs:46661, chú thích tham chiếu tại 46644-46647.",
    },
    {
      index: 2,
      id: 52,
      ten: "Thể huyết bội tăng",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Tăng % Max HP, cộng trực tiếp vào công thức CharacterMax_HP.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8041, đổ vào PlayersBes.cs:2124.",
    },
    {
      index: 3,
      id: 53,
      ten: "Tẩy tủy dịch cân",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Tăng % Max MP, tương tự idx2.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8044, đổ vào PlayersBes.cs:2126.",
    },
    {
      index: 4,
      id: 54,
      ten: "Diệu thủ hồi xuân",
      loai: "goc",
      heSo1: 2.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng thẳng vào lượng máu hồi của các chiêu hồi máu Đại Phu (501201/501202/501203). Không phải xác suất, không có rủi ro overflow.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs 42540, 42561, 42584.",
    },
    {
      index: 5,
      id: 55,
      ten: "Trường công kích lực",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Nhân hệ số vào sát thương đòn tay/chiêu Đại Phu ở cả PvE lẫn PK. Hệ số nhỏ, không rủi ro overflow.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs dòng 41386 (PvE), 45024 (PK).",
    },
    {
      index: 6,
      id: 185,
      ten: "Khí trầm đan điền",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Slot dùng chung mọi nghề (DonKhi_DanDien), quy đổi % phòng ngự hiện có thành cả HP cộng thêm lẫn Lực Phòng Ngự Võ Công cộng thêm, thụ động, tính ngay trong UpdateKhiCong().",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs case6 job5; tiêu thụ chung PlayersBes.cs~8537-8542 (đối chiếu 3+ nghề khác trong đợt audit xác nhận field này CÓ tiêu thụ — sửa lại từ đánh giá 'chết' ban đầu do grep sót).",
    },
    {
      index: 7,
      id: 57,
      ten: "Chân vũ tuyệt kích",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 1.3,
      batBuocThangThien: null,
      moTa: "Proc nhân sát thương: nếu roll trúng thì nhân thẳng hệ số 1.3 tại thời điểm tiêu thụ (không nhân qua điểm đầu tư). Field dùng chung với Đao/HanBaoQuan/Tử Hào theo ID riêng từng nghề.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs 41387-41390 (PvE), 45025-45029 (PK). Xác suất tối đa ~70-80%, không vượt trần.",
    },
    {
      index: 8,
      id: 56,
      ten: "Hấp tinh đại pháp",
      loai: "goc",
      heSo1: 15.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Kéo dài thời lượng các buff chủ động họ Cửu Thiên Chân Khí. Chỉ tác động thời lượng, không phải xác suất, không rủi ro overflow.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs ~42892, 42928, 42964, 43000, 43040, 43080, 43104, 43166, 43442, 43504, 43566.",
    },
    {
      index: 9,
      id: 350,
      ten: "Cuồng ý hộ thể",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "2 proc độc lập dùng Random() riêng khi thi triển chiêu 501203: cộng 5% Max SP, và cấp trạng thái kèm hệ số hồi phục. Trần đầu tư không chạm ngưỡng roll nên không có nguy cơ vượt trần.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs 42591-42648, 42623-42652.",
    },
    {
      index: 10,
      id: 351,
      ten: "Vô trung sinh hữu",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 1.0,
      batBuocThangThien: null,
      moTa:
        "Cổng proc ngoài cho việc nhân sát thương đòn tay/chiêu: roll trúng thì rẽ tiếp vào 1 trong 2 nhánh dựa theo khí công Thăng Thiên 'Minh Kính Chỉ Thủy' (id352): nhánh ×1.6 (khi id352 cũng trúng roll) hoặc else ×1.1. Bản thân cổng proc (hệ số 1.0, trần ~70-80 điểm) hoạt động đúng; lỗi nằm ở nhánh con id352 (xem entry đó).",
      trangThai: "DA_SUA",
      ghiChu: "Players.cs dòng 41392 (PvE), 45030 (PK). Nhánh else ×1.1 từng gần như không bao giờ thực thi do id352 vượt trần — đã sửa (xem id352).",
    },
    {
      index: 11,
      id: 59,
      ten: "Cửu thiên chân khí",
      loai: "goc",
      heSo1: 0.006,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Đa dụng: cộng thêm lượng hồi máu skill Đại Phu, và là biên độ buff toàn đội khi cast buff tự động (ATT/DEF/CX/NT/HP).",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs 42540/42561/42584 + loạt case 42892-43570; Players.cs 77071-77107 (buff toàn đội).",
    },
    {
      index: null,
      id: 58,
      ten: "Thăng Thiên 1: Hộ thân khí giáp",
      loai: "thang_thien",
      heSo1: 0.005,
      heSo2: null,
      batBuocThangThien: 6,
      moTa: "Không gate theo job — cộng thẳng vào Lực Phòng Ngự Võ Công (ULPT), thụ động.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8574, đổ vào TotalSkillDefense PlayersBes.cs:2148.",
    },
    {
      index: null,
      id: 150,
      ten: "Thăng Thiên 2: Vạn vật hồi xuân",
      loai: "thang_thien",
      heSo1: 1.0,
      heSo2: null,
      batBuocThangThien: 7,
      moTa: "Proc nhân đôi lượng hồi máu của các chiêu Đại Phu. Xác suất tối đa ~70-80%, không vượt trần.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs 42541-42545, 42562-42566, 42609-42617, 42653-42663.",
    },
    {
      index: null,
      id: 352,
      ten: "Thăng Thiên 3: Minh kính chỉ thủy",
      loai: "thang_thien",
      heSo1: 2.0,
      heSo2: null,
      batBuocThangThien: 8,
      moTa:
        "Nhánh proc LỒNG bên trong proc của khí công gốc 'Vô trung sinh hữu' (idx10). BUG: hệ số 2.0/điểm trong khi ngưỡng roll là RNG.Next(1,100) (bao gồm cận trên) — chỉ cần đầu ≥50 điểm là giá trị đã ≥100, khiến roll LUÔN ĐÚNG. Kết quả: từ mốc ~50 điểm trở lên, nhánh ×1.6 luôn thắng, nhánh else ×1.1 của idx10 chết hẳn. Vì đây là khí công Thăng Thiên bậc 8, người chơi tới bậc đó thường đầu khá sâu nên tình trạng vượt mốc 50 gần như luôn xảy ra trên server thật.",
      trangThai: "DA_SUA",
      ghiChu:
        "Players.cs dòng 41394-41403 (PvE), 45032-45041 (PK). ĐÃ SỬA 03/09: bọc Math.Min(giá trị,99.0) ở cả 2 vị trí — nhánh ×1.6 vẫn ưu tiên khi trúng nhưng không còn LUÔN đúng, nhánh else ×1.1 khôi phục lại cơ hội xảy ra.",
    },
    {
      index: null,
      id: 353,
      ten: "Thăng Thiên 4: Mãn nguyệt cuồng phong",
      loai: "thang_thien",
      heSo1: 0.05,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Field dùng chung nhiều nghề tier Thăng Thiên 4. Proc buff cả đội theo TeamID, hệ số nhỏ nên xác suất tối đa chỉ ~3.5-4%.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8583; Players.cs:46389.",
    },
    {
      index: null,
      id: 354,
      ten: "Thăng Thiên 4: Vọng mai thiêm hoa",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Field dùng chung (cũng id614 nghề khác). Proc buff HP/MP +1000 cho đội khi có chiêu VoCongMoi[1,25]. Xác suất tối đa ~35-40%, không vượt trần.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8740; Players.cs:42493, 46250-46294.",
    },
    {
      index: null,
      id: 387,
      ten: "Thăng Thiên 1: Cuồng phong thiên ý",
      loai: "thang_thien",
      heSo1: 1.0,
      heSo2: null,
      batBuocThangThien: 6,
      moTa: "Khí công ĐỘC QUYỀN Đại Phu (gate 'Player_Job==5' riêng, khác nhóm 380-386 dùng chung). Xem mô tả đầy đủ trong nhóm khí công dùng chung.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs:8636-8639. Roll RNG.Next(1,150) — mẫu 150 thay vì 100, nhiều khả năng thiết kế tránh lỗi vượt trần.",
    },
    {
      index: null,
      id: 574,
      ten: "Khí công bí cấp (Thăng Thiên 6 thức - Đại Phu)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 11,
      moTa:
        "Gán vào field ThangThien_6_JOB_5_KHI_CONG_1. Tiêu thụ tại 2 vị trí — CẢ HAI đều nằm trong nhánh PHÒNG THỦ (kiểm tra 'value3.Player_Job==5', tức khi Đại Phu là người BỊ tấn công), cùng khối với khí công nullify 'Hình Di Yêu Tương' (id683). Roll trúng chỉ hiện thông báo — KHÔNG có dòng giảm sát thương/cộng chỉ số nào theo sau.",
      trangThai: "CON_LOI_CHUA_SUA",
      ghiChu:
        "PHÁT HIỆN MỚI 09/2026, ngoài phạm vi audit 02/09. PlayersBes.cs:8882; Players.cs ~40405 (PvE), ~45690 (PK), cả 2 đều trong dispatch phòng thủ theo nghề đối thủ. ĐÍNH CHÍNH so với ghi chú trước: KHÔNG cùng ngữ cảnh với job8 id577 (id577 nằm ở phía TẤN CÔNG, lồng trong proc Chân Vũ Tuyệt Kích — 2 vị trí không so sánh trực tiếp được). Do nằm cùng khối với 1 khí công NULLIFY sát thương, nhiều khả năng công thức dự kiến là GIẢM sát thương nhận vào (không phải nhân dame tấn công như suy đoán ban đầu), nhưng không đủ căn cứ để tự viết công thức — cần Admin xác nhận ý đồ thiết kế trước khi sửa.",
    },
    {
      index: null,
      id: 683,
      ten: "[Y Sư] Khí công bí cấp thư (Hình di yêu tương, Thăng Thiên 5 thức)",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 10,
      moTa:
        "Field riêng ThangThien_5_HinhDiYeuTuong, ultimate phòng thủ tối thượng của Đại Phu. Khi bị tấn công, roll trúng thì VÔ HIỆU HOÀN TOÀN đòn đánh đến (dame=0).",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs:8773. Players.cs 40394-40397 (PvE), 45652-45657 (PK). Hệ số 0.5, trần ~70-80 điểm cho xác suất miễn nhiễm tối đa ~35-40%, không vượt trần dù hiệu ứng rất mạnh.",
    },
    {
      index: null,
      id: null,
      ten: "Thần Nông Tiên Thuật",
      loai: "goc",
      heSo1: null,
      heSo2: null,
      batBuocThangThien: null,
      moTa:
        "Khí công MỒ CÔI — không thuộc 12 khí công gốc lẫn Thăng Thiên nào của job5 (không có PID/KhiCongID tương ứng). PlayersBes.cs chỉ reset field về 0.0 mà KHÔNG có case nào gán giá trị. Tiêu thụ duy nhất: tỉ lệ chế dược thành công = random.Next(0,110) <= 80.0 + field — vì field luôn = 0.0, tỉ lệ luôn cố định ~72.7%, không phụ thuộc bất kỳ khí công nào.",
      trangThai: "CHET_HOAN_TOAN",
      ghiChu: "PlayersBes.cs:6326 (reset). Players.cs:7274 (tiêu thụ). Không rõ ý đồ thiết kế gốc, chưa tự chế công thức.",
    },
  ],
};
