import type { NgheData } from "./types";

export const JOB_07_CAM_SU: NgheData = {
  job: 7,
  tenNghe: "Cầm Sư",
  khiCong: [
    {
      index: 0,
      id: 80,
      ten: "Chiến mã bôn đằng",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Tăng công kích cơ bản, công thức tuyến tính đơn giản, không roll.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case7 idx0, ~8124-8132.",
    },
    {
      index: 1,
      id: 81,
      ten: "Thu giang dạ bạc",
      loai: "goc",
      heSo1: 16.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng thẳng máu tối đa. Flat, không proc.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case7 idx1, dòng 8135.",
    },
    {
      index: 2,
      id: 82,
      ten: "Thanh tâm phổ thiện",
      loai: "goc",
      heSo1: 1.2,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng thêm MP tối đa theo %. Flat, không proc.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case7 idx2, dòng 8138.",
    },
    {
      index: 3,
      id: 83,
      ten: "Dương quan tam điệp",
      loai: "goc",
      heSo1: 5.0,
      heSo2: 5.0,
      batBuocThangThien: null,
      moTa: "Cộng phòng ngự cơ bản (hệ số1) và lực phòng ngự võ công/ULPT (hệ số2 riêng). Cộng thẳng theo điểm, không roll.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case7 idx3, dòng 8140-8143.",
    },
    {
      index: 4,
      id: 84,
      ten: "Hán cung thu nguyệt",
      loai: "goc",
      heSo1: 0.005,
      heSo2: 0.002,
      batBuocThangThien: null,
      moTa: "Tăng % sát thương đòn đánh (CAMSU_TruongCongKichLuc = điểm×0.005, tối đa +40%). Áp dụng nhân dame ở cả PvE lẫn PK.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs case7 idx4, dòng 8146. PvE Players.cs~41560 (đúng từ đầu). PK ~45234-45245 TRƯỚC ĐÂY gọi nhầm hằng số DB thô 0.002 (không nhân điểm) khiến full 80 điểm PK chỉ +0.2% thay vì +40% như PvE — ĐÃ SỬA dùng đúng field khớp PvE. Log VET_CAMSU_TCKL.",
    },
    {
      index: 5,
      id: 85,
      ten: "Cao sơn lưu thủy",
      loai: "goc",
      heSo1: 1.2,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Giảm % phí MP khi cast chiêu (max 80×1.2=96). 🔴 BUG NGHIÊM TRỌNG NHẤT TOÀN BỘ ĐỢT AUDIT — EXPLOIT MP VÔ HẠN: tỉ lệ giảm phí = giá trị×0.015, tối đa 144%. Vượt 100% khiến biến mp cục bộ thành ÂM → NhanVat_MP -= (âm) = CỘNG MP thay vì trừ; chỉ cần ≥56/80 điểm là mọi lần cast chiêu HOÀN LẠI NHIỀU MP HƠN phí bỏ ra → spam chiêu vô hạn. So với Đại Phu/Thần Nữ dùng ×0.01 (max 80%, an toàn) — riêng Cầm Sư dùng ×0.015 sai lệch rõ.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs case7 idx5, dòng 8149. MagicUse Players.cs case7 ~46642-46657. ĐÃ SỬA: chặn trần tiLeGiamPhiMp ở 0.8 khớp mẫu Đại Phu/Thần Nữ. Log VET_CAMSU_MP. Cổng mở khoá 20 điểm (Tam Khúc Hòa Minh) không đổi, không phải bug.",
    },
    {
      index: 6,
      id: 187,
      ten: "Khí trầm đan điền",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Field dùng chung nhiều nghề, cộng thêm phòng ngự theo %. Flat, không roll.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case7 idx6, dòng 8152; tiêu thụ chung PlayersBes.cs 8537-8539.",
    },
    {
      index: 7,
      id: 86,
      ten: "Nhạc dương tam túy",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.006,
      batBuocThangThien: null,
      moTa: "Hệ số nhân dame combo khi ở trạng thái 900402 (tối đa +45%), và tăng số mục tiêu AoE khi kết hợp Loan Phượng Hòa Minh.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case7 idx7, dòng 8155. Players.cs PvE ~41719, PK ~45383, AoE ~46836-46840.",
    },
    {
      index: 8,
      id: 87,
      ten: "Mai hoa tam lộng",
      loai: "goc",
      heSo1: 0.02,
      heSo2: 0.006,
      batBuocThangThien: null,
      moTa:
        "CAMSU_MaiHoaTamLong = điểm×0.02, nhân ×100.0 để so với roll RNG quyết định proc buff phòng thủ (Tam Khúc Hòa Minh stance). Giá trị có thể lên tới 160, từ ~50-63% điểm đầu tư trở lên proc LUÔN NỔ, mất tính random. ĐÃ SỬA: bọc Math.Min(giá trị,99.0) ở cả 4 vị trí.",
      trangThai: "DA_SUA",
      ghiChu: "PvE Players.cs ~41567, ~41593; PK ~45248, ~45272. Log VET_CAMSU_MHTL.",
    },
    {
      index: 9,
      id: 88,
      ten: "Loan phượng hòa minh",
      loai: "goc",
      heSo1: 0.2,
      heSo2: 0.006,
      batBuocThangThien: null,
      moTa: "Cộng thêm khí công Thăng Thiên 'Phi Hoa Điểm Thúy' vào cùng ngưỡng roll để proc buff/tăng dame Tam Hoa Huyền.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "Kiến trúc 'cộng 2 khí công vào 1 roll' — tổng hiện tại ~30-32 trên nền roll 100-120, còn dư biên độ lớn so với trần. RÀ LẠI 03/09: xác nhận không gây behavior sai, chuyển từ CON_LOI_CHUA_SUA sang bình thường; vẫn cần theo dõi nếu hệ số DB tăng sau này. PlayersBes.cs case7 idx9, dòng 8168. Players.cs ~41630, 41724, 41734 (PvE), 45303, 45389, 45399 (PK).",
    },
    {
      index: 10,
      id: 89,
      ten: "Dương minh xuân hiểu",
      loai: "goc",
      heSo1: 0.1,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Chuỗi debuff độc/giảm dame lên NPC, nhiều roll với ngưỡng tối đa ~4-8%, an toàn.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs case7 idx10, dòng 8171; Players.cs ~41638-41710. Bug RNG.Next(1,50) bao gồm cận trên trong cùng khối đã được sửa từ trước (bản .68), không phải phát hiện mới.",
    },
    {
      index: 11,
      id: 180,
      ten: "Tiêu tương vũ dạ",
      loai: "goc",
      heSo1: 0.1,
      heSo2: 0.006,
      batBuocThangThien: null,
      moTa: "Tương tự Dương Minh Xuân Hiểu nhưng gây debuff giảm phòng ngự NPC, ngưỡng roll tối đa ~4-8%, an toàn.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case7 idx11, dòng 8174; Players.cs ~41647-41707.",
    },
    {
      index: null,
      id: 390,
      ten: "Thăng thiên 1: Phi hoa điểm thúy",
      loai: "thang_thien",
      heSo1: 1.0,
      heSo2: null,
      batBuocThangThien: 6,
      moTa:
        "Cộng thêm ×0.2 vào ngưỡng roll Loan Phượng Hòa Minh (idx9), tăng hệ số dame khi proc, và tăng số mục tiêu đòn AoE của Nhạc Dương Tam Túy khi ở trạng thái 900403.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs case390, dòng 8642. Trước 31/08 công thức số mục tiêu AoE luôn làm tròn xuống còn 2 dù đầu bao nhiêu điểm — ĐÃ SỬA (comment 31/08, Players.cs ~46849-46874): đổi sang random hoá xác suất, giữ đúng kỳ vọng trung bình nhưng khiến điểm đầu tư có tác dụng thật lên số mục tiêu.",
    },
    {
      index: null,
      id: 391,
      ten: "Thăng thiên 2: Tam đàm ánh nguyệt",
      loai: "thang_thien",
      heSo1: 0.2,
      heSo2: null,
      batBuocThangThien: 7,
      moTa:
        "Proc RNG.Next(1,100) (tối đa 14%, an toàn) khi nhân vật sắp bị đánh chết bởi đối phương có kích hoạt hiệu ứng này — gây thêm sát thương lên chính nhân vật hiện tại, có thể dẫn tới Player_Die() — dạng 'phản đòn/rút máu' đi kèm chiêu.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case391, dòng 8645; Players.cs ~48879-48904.",
    },
    {
      index: null,
      id: 392,
      ten: "Thăng thiên 3: Tử dạ thu ca",
      loai: "thang_thien",
      heSo1: 1.0,
      heSo2: null,
      batBuocThangThien: 8,
      moTa: "Nhân thêm vào hệ số dame combo của Nhạc Dương Tam Túy, ở mức tối đa nhân gốc lên khoảng x3.26. Không so với roll RNG nên không có nguy cơ tràn ngưỡng.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case392, dòng 8648; Players.cs PvE ~41719-41722, PK ~45383-45387.",
    },
    {
      index: null,
      id: 393,
      ten: "Thăng thiên 4: Mãn nguyệt cuồng phong",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Field dùng chung nhiều nghề. Proc buff +1000 HP/MP tối đa cho cả đội, tự làm mới khi proc lại.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case393, dòng 8651; Players.cs ~46333-46330.",
    },
    {
      index: null,
      id: 394,
      ten: "Thăng thiên 4: Huyền ti chẩn mạch (quát cốt liệu độc)",
      loai: "thang_thien",
      heSo1: 3.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa:
        "Field RIÊNG cho Cầm Sư. Proc trúng thì cộng +10% phòng ngự cho bản thân/toàn đội trong 3 giây, tự làm mới liên tục mỗi lần chiêu đủ điều kiện được tung.",
      trangThai: "DA_SUA",
      ghiChu:
        "ĐÃ SỬA 03/09: hệ số=3.5 trong khi num12 tối đa=70 → giá trị tối đa=245, vượt xa trần roll RNG.Next(1,100) — chỉ cần đầu ~29/70 điểm là ngưỡng đã ≥100, proc luôn nổ 100% thay vì có xác suất. Cùng kiểu lỗi 'hệ số×điểm vượt trần roll' đã sửa ở Mai Hoa Tam Lộng và MP Cao Sơn Lưu Thủy trong cùng nghề — nay đã thêm Math.Min(...,99.0) tại Players.cs ~46194 khớp 2 vị trí kia.",
    },
    {
      index: null,
      id: 576,
      ten: "Khí công bí cấp (Thăng Thiên 6 thức - Cầm Sư)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 11,
      moTa: "Cộng thẳng vào phòng ngự cơ bản (+=), không ghi đè lên khí công gốc idx3 vì field được reset về 0 trước khi gán tuần tự.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case576, dòng 8888-8891. Công thức flat, không proc, không phát hiện lỗi.",
    },
    {
      index: null,
      id: 685,
      ten: "[Cầm sư] Khí công bí cấp thư (Long trảo tiêm chỉ thủ, Thăng Thiên 5 thức)",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 10,
      moTa: "Field RIÊNG cho Cầm Sư, không dùng chung. Proc RNG.Next(1,100) (tối đa 35%, an toàn), khi trúng nhân thêm dame ×1.2 ở cả PvE và PK.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case685, dòng 8778-8780; Players.cs PvE ~41741, PK ~45407.",
    },
  ],
};
