import type { NgheData } from "./types";

export const JOB_04_CUNG: NgheData = {
  job: 4,
  tenNghe: "Cung",
  khiCong: [
    {
      index: 0,
      id: 40,
      ten: "Bách bộ xuyên dương",
      loai: "goc",
      heSo1: 0.02,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng thẳng % trúng địch (chính xác), thụ động, có hiệu lực mọi lúc.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~7987. Tiêu thụ PlayersBes.cs ~2104.",
    },
    {
      index: 1,
      id: 41,
      ten: "Liệp ưng chi nhãn",
      loai: "goc",
      heSo1: 0.05,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Mở rộng tầm công kích tối đa (bắn xa hơn), áp dụng cả 4 đường (PvE/PK, tay/chiêu).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~7990; Players.cs 38931/39557/42286/44471.",
    },
    {
      index: 2,
      id: 42,
      ten: "Ngưng thần tụ khí",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng thẳng công kích cơ bản, áp dụng mọi đòn đánh.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~7994-8000, đổ vào PlayersBes.cs ~2074.",
    },
    {
      index: 3,
      id: 44,
      ten: "Cuồng phong vạn phá",
      loai: "goc",
      heSo1: 3000.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Kéo dài thời lượng trạng thái Nộ Khí Xung Thiên, field dùng chung nhiều nghề.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs ~8003; Players.cs ~69569-69615. Lưu ý cân bằng: hệ số DB 3000/điểm rất lớn so với các nghề khác cùng slot — đáng để Admin xem lại, không phải bug code.",
    },
    {
      index: 4,
      id: 45,
      ten: "Chính bản bồi nguyên",
      loai: "goc",
      heSo1: 8.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng thẳng HP tối đa, thụ động.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~8006, đổ vào PlayersBes.cs ~2124.",
    },
    {
      index: 5,
      id: 48,
      ten: "Nhuệ lợi chi tiễn",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.01,
      batBuocThangThien: null,
      moTa:
        "CUNG_NhueLoiChiTien = 5.0 + điểm×1.0. Cộng thẳng vào dame mỗi đòn, không roll. Đòn tay (PvE+PK) đúng từ đầu. Ở CHIÊU trước đây dùng nhầm hằng số DB thô (không nhân điểm đầu tư) — ĐÃ SỬA dùng đúng field đã scale, khớp đòn tay.",
      trangThai: "DA_SUA",
      ghiChu: "PlayersBes.cs ~8009; Players.cs PvE-tay 39238, PK-tay 39783, PvE-chiêu 41324, PK-chiêu 44976.",
    },
    {
      index: 6,
      id: 184,
      ten: "Khí trầm đan điền",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Slot dùng chung mọi nghề, quy đổi % phòng ngự hiện có thành HP cộng thêm, thụ động.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~8012; tiêu thụ PlayersBes.cs ~8537-8540.",
    },
    {
      index: 7,
      id: 46,
      ten: "Tâm thần ngưng tụ",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 2.0,
      batBuocThangThien: null,
      moTa:
        "CUNG_TamThanNgungTu = 10.0 + điểm×1.0, hệ số 2 dùng làm hệ số nhân khi proc. 4 vị trí tiêu thụ đều roll riêng, không cộng ngưỡng với khí công khác.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~8015; Players.cs 39239-39244, 39795-39799, 41328-41334, 45002-45008.",
    },
    {
      index: 8,
      id: 47,
      ten: "Lưu tinh tam thỉ",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "CUNG_LuuTinhTamThi = 1.0 + điểm×1.0. PvE tay là vị trí DUY NHẤT cộng chung ngưỡng roll với khí công Thăng Thiên 'Tuyệt Ảnh Xạ Hồn' (id340) — không có trần, có thể vượt roll 100. ĐÃ SỬA: bọc Math.Min(tổng, 99.0). 3 vị trí khác code đúng từ đầu, roll riêng.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs ~8018; Players.cs PvE-tay 39262 (sửa), PK-tay 39862, PvE-chiêu 41366, PK-chiêu 44982.",
    },
    {
      index: 9,
      id: 43,
      ten: "Hồi lưu chân khí",
      loai: "goc",
      heSo1: 30000.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Kéo dài thời lượng các skill buff chủ động của chính Cung (+30 giây/điểm).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~8021; Players.cs 42690/42712/42734/42837/42861, 49635-49640.",
    },
    {
      index: 10,
      id: 49,
      ten: "Vô minh ám thỉ",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "CUNG_VoMinhAmThi = điểm×1.0, proc nhân dame ×(1+X×0.01). 4 vị trí: PvE-tay, PK-tay đúng. Ở PvE-chiêu, VoMinhAmThi/Thiên Ngoại Tam Thỉ(342)/Thiên Lý Nhất Kích(682) là chuỗi else-if loại trừ nhau đúng thiết kế.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs ~8024; Players.cs 39252, 39852, 41344-41365 (đúng). ĐÃ SỬA 03/09: PK-chiêu (~44977-45033) trước đây là 3 khối if độc lập (VoMinhAmThi/342/682) cộng dồn nhân chồng — nay dựng lại thành else-if giống PvE-chiêu, đồng thời bổ sung combo lồng id340 (trước đây vắng mặt hoàn toàn ở PK-chiêu). Cùng đợt sửa với id340/342/682.",
    },
    {
      index: 11,
      id: 140,
      ten: "Trí mệnh tuyệt sát",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.015,
      batBuocThangThien: null,
      moTa:
        "CUNG_TriMenhTuyetSat = 1.0 + điểm×1.0, nhân thêm hệ số 2 khi proc. Có mặt PvE tay, PvE chiêu, PK chiêu — HOÀN TOÀN VẮNG MẶT ở PK đòn tay (biến roll đã khai báo sẵn nhưng không dùng — dấu hiệu bỏ sót). ĐÃ SỬA: bổ sung nhánh còn thiếu vào PK đòn tay.",
      trangThai: "DA_SUA",
      ghiChu: "PlayersBes.cs ~8027; Players.cs PvE-tay 39246, PK-tay 39841-39850 (mới bổ sung), PvE-chiêu 41335-41341, PK-chiêu 45009-45014.",
    },
    {
      index: null,
      id: 340,
      ten: "Thăng thiên 1 — Tuyệt ảnh xạ hồn",
      loai: "thang_thien",
      heSo1: 1.5,
      heSo2: null,
      batBuocThangThien: 6,
      moTa:
        "3 nhóm tiêu thụ: (1) PvE-tay — cộng chung ngưỡng roll với idx8 Lưu Tinh Tam Thỉ, đã sửa trước đó. (2) PvE-chiêu — bonus 'combo' x1.25 dame LỒNG bên trong nhánh proc 342 (Thiên Ngoại Tam Thỉ), roll riêng. (3) Số mục tiêu AoE (đánh NPC +2/+5 mục tiêu, PK +3 mục tiêu), roll riêng.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs ~8718; Players.cs 39262 (đã sửa). ĐÃ SỬA 03/09: DB hệSố=1.5/điểm, trần điểm mặc định 70 → giá trị tối đa ~105 vượt ngưỡng RNG.Next(1,100) khiến proc luôn 100% từ ~67 điểm — đã chặn Math.Min(...,99.0) ở cả 2 vị trí AoE-số-mục-tiêu (46826/46979) và combo PvE-chiêu (41357-41372). Đồng thời bổ sung nhánh combo id340 còn thiếu hoàn toàn ở PK-chiêu (nằm trong đợt dựng lại else-if của idx10).",
    },
    {
      index: null,
      id: 341,
      ten: "Thăng thiên 2 — Thiên quân áp đà",
      loai: "thang_thien",
      heSo1: 5.0,
      heSo2: null,
      batBuocThangThien: 7,
      moTa: "2 field passive: nới giới hạn trọng lượng mang vác, và cộng thẳng phòng ngự cơ bản (dùng đúng hệ số DB). Luôn có hiệu lực, không proc.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~8720-8723, đổ vào PlayersBes.cs ~2087. Hằng số trọng lượng 0.003 viết cứng là chủ ý, không phải lỗi.",
    },
    {
      index: null,
      id: 342,
      ten: "Thăng thiên 3 — Thiên ngoại tam thỉ",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 8,
      moTa:
        "PvE-chiêu: else-if trong chuỗi loại trừ với VoMinhAmThi/682, roll trúng khi chiêu cấp≥5, nhân ×1.5 kèm combo lồng 340 bên trong.",
      trangThai: "DA_SUA",
      ghiChu: "PlayersBes.cs ~8725; Players.cs PvE-chiêu 41350-41358. ĐÃ SỬA 03/09: PK-chiêu trước đây là if độc lập (không else-if), không có combo 340 — nay dựng lại else-if khớp PvE-chiêu, xem chi tiết ở idx10.",
    },
    {
      index: null,
      id: 343,
      ten: "Thăng thiên 4 — Mãn nguyệt cuồng phong",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Field dùng chung nhiều nghề ở tier Thăng Thiên 4. Proc buff hồi máu đồng đội khi có team, hoạt động đúng thiết kế.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~8728 (share với case 373/327/353/613); Players.cs ~46389.",
    },
    {
      index: null,
      id: 344,
      ten: "Thăng thiên 4 — Liệt nhật viêm viêm",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa:
        "Field dùng chung (share với case 374/326/614). Tiêu thụ trong AscensionFourQigongTrigger (yêu cầu Level>=140, Thăng Thiên>=9): debuff -15% phòng ngự đối phương 3s. Hàm được gọi Playe=null ở PvE-tay nên KHÔNG có tác dụng khi đánh quái; có tác dụng thật khi PK-tay.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~8731; Players.cs 46071-46093 (hàm), 39141 (gọi null, PvE no-op), 40603 (gọi thật, PK).",
    },
    {
      index: null,
      id: 573,
      ten: "Khí công bí cấp (Thăng Thiên 6 thức - Cung, Ác Tàn Thi Cung)",
      loai: "thang_thien",
      heSo1: 0.007,
      heSo2: null,
      batBuocThangThien: 11,
      moTa:
        "Buff dame tấn công của chính Cung, cộng dồn theo điểm đầu tư (base.AcTanThiCung × hệ số).",
      trangThai: "DA_SUA",
      ghiChu: "PlayersBes.cs ~8879; Players.cs 39712, 39747, 40607, 40715, 45990. ĐÃ SỬA 03/09: cả 5 vị trí trước đây đọc nhầm 'value3.AcTanThiCung' (value3 là đối thủ/mục tiêu, không phải người tấn công) khiến Cung đầu điểm không được lợi gì còn mục tiêu bị đánh (nếu là Cung có đầu điểm) lại vô tình bị cộng thêm sát thương phải nhận — nay đổi toàn bộ 5 vị trí thành base.AcTanThiCung.",
    },
    {
      index: null,
      id: 682,
      ten: "[Cung] Khí công bí cấp thư (Thăng Thiên 5 thức - Thiên lý nhất kích)",
      loai: "thang_thien",
      heSo1: 1.0,
      heSo2: null,
      batBuocThangThien: 10,
      moTa:
        "base.ThangThien_5_ThienLyNhatKich = điểm×1.0, standalone. 4 vị trí, roll RNG.Next(1,100) độc lập, nhân ×(1+X×2.0/100) khi trúng. Đường tay (PvE/PK) không có vấn đề gì.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs ~8770; Players.cs PvE-tay 39257, PK-tay 39857, PvE-chiêu 41360-41365 (đúng). ĐÃ SỬA 03/09: PK-chiêu (~45016-45020) trước đây tách if độc lập thay vì else-if như PvE-chiêu, có thể cộng dồn nhân chồng với VoMinhAmThi(idx10)/ThienNgoaiTamThi(342) — nay dựng lại else-if khớp PvE-chiêu, cùng đợt sửa với idx10/342/340.",
    },
  ],
};
