import type { NgheData } from "./types";

// job=8 KHÔNG PHẢI Thần Nữ — tên nội bộ code "HanBaoQuan". Tên hiển thị thật trong game xác
// nhận qua QigongControl.cs:2393 (mảng tên 13 nghề GUI admin): "Hàn Bảo Quân".
export const JOB_08_HAN_BAO_QUAN: NgheData = {
  job: 8,
  tenNghe: "Hàn Bảo Quân",
  khiCong: [
    {
      index: 0,
      id: 250,
      ten: "Lực phách hoa sơn",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.01,
      batBuocThangThien: null,
      moTa: "Cộng thẳng vào lực công kích cơ bản, dùng chung mọi nghề. Áp dụng mọi đòn tay/chiêu, PK/PvE.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case0 job8, dòng 8181-8190.",
    },
    {
      index: 1,
      id: 251,
      ten: "Lhiếp hồn nhất kích",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng vào chính xác (trúng địch) cơ bản, dùng chung công thức mọi nghề.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case1 job8, dòng 8191-8193.",
    },
    {
      index: 2,
      id: 252,
      ten: "Thiên ma cuồng huyết",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Chỉ phát huy ở CHIÊU (PK+PvE): roll trúng thì nhân dame ×1.2 và đặt cờ kích hoạt kép.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs case2 job8: nhánh X2 (HanBaoQuan_ThienMaCuongHuyetX2) dùng hệ số DB rate2, trước đây =0.0 → LUÔN = 0 bất kể đầu bao nhiêu điểm. ĐÃ SỬA 03/09 (Admin xác nhận): UPDATE TBL_XWWL_SKILL SET FLD_BonusRateValuePerPoint2=0.01 WHERE FLD_JOB=8 AND FLD_INDEX=2 — mirror đúng giá trị rate1 hiện có, không tự chế số mới. Field X2 này còn là điều kiện kích hoạt cho 2 khí công Thăng Thiên khác (601, 686) — cả 2 tự động sống lại theo, xem 2 mục đó.",
    },
    {
      index: 3,
      id: 253,
      ten: "Bách biến thần hành",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.001,
      batBuocThangThien: null,
      moTa: "Cộng vào % né tránh cơ bản, dùng chung công thức mọi nghề.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case3 job8, dòng 8198-8200.",
    },
    {
      index: 4,
      id: 254,
      ten: "Cuồng phong vạn phá",
      loai: "goc",
      heSo1: 3000.0,
      heSo2: 0.05,
      batBuocThangThien: null,
      moTa: "Kéo dài thời lượng trạng thái Nộ Khí Xung Thiên, field dùng chung nhiều nghề.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case4 job8; Players.cs ~69569-69573.",
    },
    {
      index: 5,
      id: 255,
      ten: "Truy cốt hấp nguyên",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Giảm % sát thương nhận vào: roll trúng thì trừ bớt % đó khỏi damage sắp nhận, áp dụng cả khi bị NPC lẫn người chơi đánh.",
      trangThai: "DA_SUA",
      ghiChu:
        "Hoán đổi với index6 — xem PlayersBes.cs case5/case6 job8 (dòng 8204-8216). DB xác nhận index5 tên 'Truy cốt hấp nguyên', index6 tên 'Khí trầm đan điền'; code cũ gán ngược. ĐÃ SỬA hoán đổi lại, rate DB 2 slot bằng nhau (0.5/0.5) nên độ lớn không đổi. Bằng chứng phụ: item attribute VatPham_ThuocTinh_ThemVao_HanBaoQuan_TruyCotHapNguyen vốn đã map đúng slot 5 từ trước.",
    },
    {
      index: 6,
      id: 188,
      ten: "Khí trầm đan điền",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Buff HP + phòng ngự chung. Chạy sau toàn bộ switch job, áp dụng chung mọi nghề có field >0.",
      trangThai: "DA_SUA",
      ghiChu: "Hoán đổi với index5 — xem chi tiết ở mục index5.",
    },
    {
      index: 7,
      id: 256,
      ten: "Bá khí phá giáp",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 1.2,
      batBuocThangThien: null,
      moTa:
        "Đòn/chiêu PK: roll trúng thì giảm phòng ngự đối phương theo hệ số DB. Đủ ở cả 4 vị trí (giống hệt bug của Đao, đọc cùng field PhaGiap_TiLe).",
      trangThai: "DA_SUA",
      ghiChu:
        "PK tay/chiêu TRƯỚC ĐÂY nhân THẲNG vào phòng ngự đối phương — làm TĂNG giáp đối phương 20% mỗi proc (tự làm yếu chính mình). ĐÃ SỬA: nhân 0.8 = giảm giáp đối phương 20%. PvE tay/chiêu vốn đã đúng. Log VET_DAO_BKPG (dùng chung tag với Đao).",
    },
    {
      index: 8,
      id: 257,
      ten: "Chân vũ tuyệt kích",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 1.3,
      batBuocThangThien: null,
      moTa: "Chỉ phát huy ở CHIÊU: roll trúng thì nhân dame ×1.3. Field dùng chung với Tử Hào (job12) nhưng mỗi job có nhánh switch riêng.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "Players.cs PvE ~41773-41782, PK ~45427-45430. Nhánh PvE có combo lồng: nếu proc lần đầu thành công còn roll thêm với Thăng Thiên 577 để nhân dame THÊM lần nữa — xem mục Thăng Thiên 577 (bug: combo này CHỈ có ở PvE, KHÔNG có ở PK).",
    },
    {
      index: 9,
      id: 259,
      ten: "Hỏa long vấn đỉnh",
      loai: "goc",
      heSo1: 9000.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Kích hoạt qua dùng kỹ năng, 3 cấp buff công +5%/+10%/+15%, thời lượng = 10000ms + field. 3 cấp tự loại trừ nhau.",
      trangThai: "DA_SUA",
      ghiChu:
        "ĐÃ SỬA 03/09: cấp 1 và cấp 2 đều có gate 'CharacterPKMode != 0 thì return' — chỉ kích hoạt được khi không bật PK Mode. Cấp 3 (mạnh nhất +15%) trước đây THIẾU điều kiện này, có thể bật bất kỳ lúc nào kể cả đang PK — nay đã bổ sung khớp cấp 1/2. Players.cs case 1001303 (~50244-50254).",
    },
    {
      index: 10,
      id: 260,
      ten: "Lưu quang loạn vũ",
      loai: "goc",
      heSo1: 0.001,
      heSo2: 1.0,
      batBuocThangThien: null,
      moTa: "Tăng số lần trúng đòn của kỹ năng nhiều mục tiêu. Dùng chung field với Đao (job1), tách biệt qua kiểm tra job.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs AttackCalculationCompleted, ~46809-46812.",
    },
    {
      index: 11,
      id: 258,
      ten: "Ám ảnh tuyệt sát",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 1.2,
      batBuocThangThien: null,
      moTa: "Chỉ phát huy ở CHIÊU (như idx8): roll trúng thì nhân dame ×1.2. Chạy đúng công thức thiết kế.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "Players.cs PvE ~41783-41787, PK ~45432-45436. Có cộng thêm 1 số hạng lẽ ra từ Thăng Thiên 601 nhưng số hạng đó luôn =0 do cùng gốc bug idx2 — xem mục Thăng Thiên 601.",
    },
    {
      index: null,
      id: 577,
      ten: "Khí công bí cấp (Thăng Thiên 6 thức - HBQ)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 11,
      moTa: "Combo cộng thêm lồng trong proc của idx8 (Chân Vũ Tuyệt Kích): nếu idx8 đã proc, roll thêm thì nhân dame ×1.3 THÊM một lần nữa.",
      trangThai: "DA_SUA",
      ghiChu:
        "ĐÃ SỬA 03/09: field trước đây chỉ được đọc ở PvE-chiêu (Players.cs ~41792-41799) — PK-chiêu (~45459-45463) không có combo lồng này, đầu điểm vô tác dụng khi PK. Nay đã bổ sung nhánh combo id577 vào khối Chân Vũ Tuyệt Kích ở PK-chiêu, khớp cấu trúc PvE-chiêu.",
    },
    {
      index: null,
      id: 600,
      ten: "Thăng thiên 1 hành phong lộng vũ",
      loai: "thang_thien",
      heSo1: 0.7,
      heSo2: null,
      batBuocThangThien: 6,
      moTa: "Proc riêng ở chiêu: roll trúng thì nhân dame cố định ×1.25 (hard-code, không đọc DB). Có đủ ở cả PvE và PK chiêu.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "Players.cs PvE ~41788-41792, PK ~45437-45441. Bản thân proc chạy đúng cả 2 đường, không có lỗi vắng-nhánh như 577. Có cộng thêm 1 số hạng lẽ ra từ Thăng Thiên 601 nhưng luôn =0 — lỗi ở 601, không quy cho 600.",
    },
    {
      index: null,
      id: 601,
      ten: "Thăng thiên 3 thiên ma hộ thể",
      loai: "thang_thien",
      heSo1: 0.3,
      heSo2: null,
      batBuocThangThien: 7,
      moTa:
        "Thiết kế: khi Thiên Ma Cuồng Huyết (idx2) đạt trạng thái 'kích hoạt kép', cộng bonus vào ngưỡng roll của idx11 và Thăng Thiên 600, đồng thời cộng thêm 1 đòn dame lưu trữ.",
      trangThai: "DA_SUA",
      ghiChu:
        "ĐÃ SỬA 03/09 cùng lúc với idx2: field 'kích hoạt kép' chỉ được gán khi HanBaoQuan_ThienMaCuongHuyetX2 > 0.0 — trước đây field đó LUÔN = 0.0 (rate2 idx2 = 0.0) nên hiệu ứng 601 chưa từng được áp dụng. Đã bật rate2 idx2 lên 0.01 trong DB (xem idx2), 601 tự động sống lại không cần sửa riêng.",
    },
    {
      index: null,
      id: 602,
      ten: "Thăng thiên 2 nội tức hành tâm",
      loai: "thang_thien",
      heSo1: 0.02,
      heSo2: null,
      batBuocThangThien: 8,
      moTa: "Giảm nhịp hồi chiêu (haste) — nhân (1.0 - giá trị) vào mốc chống hack tốc độ đánh, dùng luôn làm nhịp cast chiêu tối thiểu.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs dòng 38522-38525.",
    },
    {
      index: null,
      id: 603,
      ten: "Thăng thiên 4 trường hồng quán thiên",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Proc AoE buff đồng minh cùng phe trong tầm 300: +100 công, +100 thủ, +1000 HP tối đa, +1000 MP tối đa, 3 giây.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs dòng 46439+. Field dùng chung khung 'Thăng Thiên 4' với job khác (case701).",
    },
    {
      index: null,
      id: 604,
      ten: "Thăng thiên 4 ai hồng biến dã",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Proc AoE debuff địch trong tầm 300: giảm 0.15 trần HP tối đa của mục tiêu, trạng thái 10 giây.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs dòng 46105-46151. Dùng chung khung Thăng Thiên 4 với case702 job khác.",
    },
    {
      index: null,
      id: 686,
      ten: "[Hàn phi quan] Khí công bí cấp thư (Thiên ma chi lực, Thăng Thiên 5 thức)",
      loai: "thang_thien",
      heSo1: 0.01,
      heSo2: null,
      batBuocThangThien: 10,
      moTa: "Hệ số cộng thêm vào đòn 'dame lưu trữ' của combo Thiên Ma Cuồng Huyết kích hoạt kép.",
      trangThai: "DA_SUA",
      ghiChu:
        "ĐÃ SỬA 03/09 cùng lúc idx2/601: dòng code duy nhất đọc field này cần HanBaoQuan_ThienMaCuongHuyetX2 > 0.0 (trước đây luôn false vì rate2 idx2 = 0.0). Đã bật rate2 idx2 lên 0.01 trong DB, 686 tự động sống lại không cần sửa riêng.",
    },
  ],
};
