import type { NgheData } from "./types";

export const JOB_06_NINJA: NgheData = {
  job: 6,
  tenNghe: "Ninja",
  khiCong: [
    {
      index: 0,
      id: 70,
      ten: "Kinh kha chi nộ",
      loai: "goc",
      heSo1: 2.0,
      heSo2: 0.1,
      batBuocThangThien: null,
      moTa:
        "Cộng ATK cơ bản, công thức giống Đao/Cung/HanBaoQuan/Quyền Sư nhưng KHÔNG chia thêm /2 — Ninja ăn trọn hệ số DB, gấp đôi mức cộng ATK so với các nghề dùng chung công thức gốc. Hệ số 2 là tốc độ hồi thanh SP mỗi đòn tay.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs:8077-8082. SP: Players.cs:39365-39368 (PhysicalAttack) và 48720-48722 (AttackConfirmation) — chưa xác minh có nguy cơ cộng 2 lần cho cùng 1 đòn hay không, cần người nắm rõ luồng gọi xác nhận thêm.",
    },
    {
      index: 1,
      id: 71,
      ten: "Tam hoa tụ đỉnh",
      loai: "goc",
      heSo1: 0.2,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "NINJA_TamHoaTuDinh = 10 + điểm×0.2, tối đa 24 ở 70 điểm — là % NÉ TRÁNH TOÀN PHẦN khi Ninja BỊ đánh (quái lẫn PK). Roll so với mẫu số phụ thuộc cường hoá bên tấn công. Khi né thành công: dame về 0, lưu lại 'đòn phản' cộng vào đòn tay KẾ TIẾP của Ninja (qua idx9).",
      trangThai: "BINH_THUONG",
      ghiChu: "NpcClass.cs:1493-1500 (quái), Players.cs:40404-40411/45675-45677 (PK). Liên kết chặt với idx9.",
    },
    {
      index: 2,
      id: 72,
      ten: "Liên hoàn phi vũ",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "% proc đòn tay 'combo múa liên hoàn' khi KHÔNG proc Tâm Thần Ngưng Tụ (idx3) trước đó. PvE roll(0,100), PK roll(1,120), dame ×2.0-2.5.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs:39359 (PvE), 39984-39997 (PK). Giá trị max 80-90 nằm dưới trần roll, không lỗi 'luôn đúng'.",
    },
    {
      index: 3,
      id: 74,
      ten: "Tâm thần ngưng tụ",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 4.1,
      batBuocThangThien: null,
      moTa:
        "% proc đòn tay MẠNH NHẤT của Ninja: khi trúng, dame ×4.0 nếu đồng thời trúng Nhất Chiêu Tàn Sát (idx11), ngược lại ×2.0-1.5; sau đó còn nhân thêm (1+idx4) nếu idx4 có điểm.",
      trangThai: "DA_SUA",
      ghiChu:
        "2 phát hiện: (1) hệ số 2 (4.1) khai báo trong DB nhưng KHÔNG có nơi nào gọi tới — 'chết', ảnh hưởng thấp, không sửa (không đủ cơ sở tự chế thêm 1 hiệu ứng). (2) ĐÃ SỬA 03/09: bug '.169 Ninja ra 100% dame xanh' trước chỉ vá ở nhánh PK bằng trần World.PK_Ninja_TamThan_TranTiLe — nhánh PvE (đòn tay đánh quái, Players.cs ~39339) không có trần này. Đã bổ sung đúng cùng khoá cấu hình vào nhánh PvE (dùng chung 1 khoá cho cả 2 đường), và BẬT khoá lên 70 trên K2 (theo đúng ví dụ hiệu chỉnh có sẵn trong code: 'đặt 70 thì còn khoảng 30% đòn thường'). Admin đã xác nhận chấp nhận đổi cân bằng PvE Ninja.",
    },
    {
      index: 4,
      id: 75,
      ten: "Trí thủ tuyệt mệnh",
      loai: "goc",
      heSo1: 0.02,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "KHÔNG phải % proc riêng — hệ số nhân THÊM khi idx3 đã proc: dame ×(1.0+giá trị), tối đa +140% ở 80 điểm. Chỉ có tác dụng khi đã đầu idx3.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs:39353-39356 (PvE), 39977-39980 (PK).",
    },
    {
      index: 5,
      id: 372,
      ten: "Dĩ nộ hoàn nộ",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.08,
      batBuocThangThien: null,
      moTa:
        "Theo DB, FLD_INDEX=5 đúng ra là 'Dĩ nộ hoàn nộ' (hệ số 1.0/0.08): % cơ hội hồi +2 Nộ Khí khi dùng 1 số chiêu combo Thiên Chu Vạn Thủ.",
      trangThai: "DA_SUA",
      ghiChu:
        "ĐÃ SỬA 03/09: PlayersBes.cs switch(i) job6 case5 (~8098-8100) trước đây gán nhầm base.DonKhi_DanDien (đáng lẽ idx6), case6 (~8101-8103) gán nhầm base.NINJA_DiNoHoanNo (đáng lẽ idx5) — nay đã hoán đổi lại đúng field, cùng dạng bug đã sửa cho job=8 (case5/6 Hàn Bảo Quân) trong đợt audit 02/09 nhưng Ninja bị bỏ sót khi đó. Lưu ý: hệ số DB 2 khí công của Ninja KHÁC nhau thật (1.0 vs 0.5, không như job8 cả hai đều 0.5) nên độ lớn buff/hồi Nộ Khí có đổi theo đúng thiết kế sau khi field khớp lại đúng tên.",
    },
    {
      index: 6,
      id: 186,
      ten: "Khí trầm đan điền",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Theo DB, FLD_INDEX=6 đúng ra là 'Khí trầm đan điền' (hệ số 0.5) — buff HP/giáp chung dùng field DonKhi_DanDien.",
      trangThai: "DA_SUA",
      ghiChu: "ĐÃ SỬA cùng lúc với idx5 — xem chi tiết đầy đủ ở đó, chỉ ghi 1 lần tránh trùng lặp.",
    },
    {
      index: 7,
      id: 76,
      ten: "Tiên phát chế nhân",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "2 tác dụng: (1) khi mang buff 801201, cộng % vào chính xác đòn tay — PvE nhân/100, PK nhân/200 (chỉ bằng nửa hệ số PvE, có thể là chủ ý làm yếu PK). (2) CỘNG THẲNG không điều kiện buff vào tỉ lệ proc Tâm Thần Ngưng Tụ (idx3).",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs 39170-39173 (PvE), 39663-39666 (PK).",
    },
    {
      index: 8,
      id: 77,
      ten: "Thiên chu vạn thủ",
      loai: "goc",
      heSo1: 1000.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Cộng thêm mili-giây vào THỜI LƯỢNG debuff chảy máu + giảm giáp NPC/đối thủ (0.3) mà chuỗi chiêu Nộ Khí của Ninja áp lên mục tiêu, tối đa +80s ở 80 điểm.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs:8108. Bug liên quan trực tiếp thời lượng debuff mà khí công này kéo dài: ở PvE đòn tay (Players.cs ~39150), code trừ THẲNG 1 số điểm giáp cố định thay vì nhân theo % (đúng ý đồ, khớp mẫu Cầm Sư 2 dòng phía trên). ĐÃ SỬA 03/09: đổi 'num4 -= 1.0 - x' thành 'num4 *= 1.0 - x' khớp đúng mẫu Cầm Sư. Đường PK không bị lỗi này, không cần đổi.",
    },
    {
      index: 9,
      id: 78,
      ten: "Liên tiêu đái đả",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Tỉ lệ QUY ĐỔI dame né được từ idx1 thành 'trữ lực', cộng vào ATK đòn tay kế tiếp rồi reset. Vô dụng nếu không có idx1.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs 39165-39169 (PvE), 39658-39662 (PK).",
    },
    {
      index: 10,
      id: 79,
      ten: "Kiếm nhận loạn vũ",
      loai: "goc",
      heSo1: 3000.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng thẳng vào THỜI LƯỢNG buff tự thân 801201 (tốc độ đánh +200), mặc định 100s, tối đa đầu tư gần +210s.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs:49789-49796. Buff 801201 là điều kiện để idx7 cộng bonus chính xác.",
    },
    {
      index: 11,
      id: 73,
      ten: "Nhất chiêu tàn sát",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.01,
      batBuocThangThien: null,
      moTa: "Chỉ roll KHI idx3 đã proc trước: roll thêm, trúng thì hệ số nhân combo đổi từ ×2.0 thành ×4.0.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs 39344-39348 (PvE), 39968-39972 (PK). Hệ số 2 (0.01) không thấy nơi nào dùng, biên độ rất nhỏ, không đủ để coi là bug.",
    },
    {
      index: null,
      id: 370,
      ten: "Thăng thiên 1 - Dạ ma triền thân",
      loai: "thang_thien",
      heSo1: 1.0,
      heSo2: null,
      batBuocThangThien: 6,
      moTa: "Kỹ năng phòng thủ: khi BỊ đánh (đòn tay), roll trúng thì giảm 30% dame nhận vào.",
      trangThai: "BINH_THUONG",
      ghiChu: "NpcClass.cs:1501-1505; Players.cs:40412-40416, 45665-45669.",
    },
    {
      index: null,
      id: 371,
      ten: "Thăng thiên 2 - Thuận thủy thôi chu",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 7,
      moTa: "Khi bị đánh, roll trúng thì hồi máu = 20% dame vừa nhận. Có thể cộng dồn cùng lúc với id370 (giảm 30% dame + hồi 20% phần dame đã giảm) — đúng ý đồ phòng thủ 2 lớp, không phải bug.",
      trangThai: "BINH_THUONG",
      ghiChu: "NpcClass.cs:1506-1509; Players.cs:40417-40421, 45670-45674.",
    },
    {
      index: null,
      id: 373,
      ten: "Thăng thiên 4 - Mãn nguyệt cuồng phong",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Field dùng chung nhiều nghề, yêu cầu Level>=140 và Thăng Thiên>=9. Buff cả đội khi trúng.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8583; Players.cs:46389.",
    },
    {
      index: null,
      id: 374,
      ten: "Thăng thiên 4 - Liệt nhật viêm viêm",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Field dùng chung. Chỉ chạy khi có mục tiêu PK thật, debuff giảm 15% phòng ngự đối thủ 3s.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8586; Players.cs:46071-46094. Có 1 điều kiện check trạng thái viết lặp 2 lần y hệt (dòng 46084), thừa code copy-paste vô hại, không đổi kết quả logic.",
    },
    {
      index: null,
      id: 575,
      ten: "Khí công bí cấp (Thăng Thiên 6 thức - Ninja)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 11,
      moTa: "Passive, không roll. Cộng thẳng vào HP (tối đa 7 lần FLD_PhongNgu ở 70 điểm), gọn trong PlayersBes.cs.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8885-8886.",
    },
    {
      index: null,
      id: 684,
      ten: "[Thứ khách] Khí công bí cấp thư (Nhất chiêu sát thần, Thăng Thiên 5 thức)",
      loai: "thang_thien",
      heSo1: 0.01,
      heSo2: null,
      batBuocThangThien: 10,
      moTa: "Field ThangThien_5_NhatChieuSatThan, ultimate bậc 10 RIÊNG của Ninja, tên gợi ý là bản nâng cấp của idx11 'Nhất Chiêu Tàn Sát'.",
      trangThai: "CHET_HOAN_TOAN",
      ghiChu:
        "PlayersBes.cs:8776 — chỉ 3 nơi trong toàn repo: khai báo property, reset về 0 (PlayersBes.cs:6415), và gán (case684). KHÔNG có bất kỳ dòng nào trong Players.cs/NpcClass.cs đọc lại field này. PHÁT HIỆN MỚI 09/2026, ngoài phạm vi audit 02/09 (Ninja không thuộc đợt đó). Khác bug idx3/idx8 (vẫn có tác dụng chính), khí công này CHẾT TOÀN PHẦN — cần Admin xác nhận có nên gắn hiệu ứng (theo tên gọi có thể là buff mạnh thêm combo idx3+idx11) hay chưa từng hoàn thiện.",
    },
  ],
};
