import type { NgheData } from "./types";

export const JOB_02_KIEM: NgheData = {
  job: 2,
  tenNghe: "Kiếm",
  khiCong: [
    {
      index: 0,
      id: 20,
      ten: "Trường hồng quán nhật",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Khí công CĂN BẢN, cộng thẳng vào lực công kích gốc (không phải %). Công thức: FLD_LonNhatCongKich × điểm × 1.0 / 100 / 3. Áp dụng cho cả đòn tay lẫn chiêu, PvE lẫn PK.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~7889-7897 (gán); PlayersBes.cs:2074 (tiêu thụ).",
    },
    {
      index: 1,
      id: 21,
      ten: "Bách biến thần hành",
      loai: "goc",
      heSo1: 0.1,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng vào % né tránh theo công thức nhân, có baseline 10% ngay cả khi chưa đầu tư điểm.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:7900 (gán); PlayersBes.cs:2120 (tiêu thụ).",
    },
    {
      index: 2,
      id: 22,
      ten: "Liên hoàn phi vũ",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Chiêu đòn tay: cơ hội (base 10% + điểm×1.0, tối đa 90% ở 80 điểm) tung liên hoàn đòn, khi trúng nhân sát thương đòn tay ×2.0. NGUYÊN NHÂN CHÍNH của báo cáo 'dame Kiếm quá to': trước đây ở PK đòn tay, Liên Hoàn Phi Vũ và Nộ Hải Cuồng Lan (idx7) là 2 khối if tách biệt, có thể NỔ CÙNG LÚC trên 1 đòn (tối đa dồn ~x2.6). ĐÃ SỬA: thêm cờ cục bộ daNoNoHaiCuongLan — Liên Hoàn Phi Vũ chỉ nổ khi Nộ Hải Cuồng Lan CHƯA nổ ở đòn đó. Phát hiện thêm cùng gốc lỗi ở đòn tay PvE: roll cũ RNG.Next(1,80) trong khi giá trị max 90 → luôn 100% ở điểm cao — ĐÃ SỬA thành RNG.Next(1,100).",
      trangThai: "DA_SUA",
      ghiChu:
        "PK tay: Players.cs ~39758-40123 (cờ daNoNoHaiCuongLan, log VET_KIEM_NHCL/VET_KIEM_LHPV). PvE tay: Players.cs ~40803-40807.",
    },
    {
      index: 3,
      id: 23,
      ten: "Phá thiên nhất kiếm",
      loai: "goc",
      heSo1: 0.6,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Không roll — hệ số nhân sát thương THƯỜNG TRỰC: điểm × 0.6 × 0.01, tối đa +48% ở 80 điểm, nhân vào MỌI đòn (tay lẫn chiêu, PvE lẫn PK).",
      trangThai: "DA_SUA",
      ghiChu:
        "ĐÃ SỬA 03/09: trước đây field chỉ được đọc ở 2 nhánh PvE, hoàn toàn vắng mặt ở PK tay/PK chiêu — đầu điểm nghĩ có tác dụng PK nhưng thực chất vô hiệu. Đã bổ sung PK tay (~39774 khối) + PK chiêu (~44982 khối), nhân độc lập ngoài chuỗi loại-trừ giống PvE. LƯU Ý CÂN BẰNG: đây là buff dame PK cố định (không phải proc hiếm) cho Kiếm — nghề vừa là nguồn gốc report 'dame Kiếm quá to' của cả đợt audit; theo dõi sát sau khi bật.",
    },
    {
      index: 4,
      id: 24,
      ten: "Cuồng phong vạn phá",
      loai: "goc",
      heSo1: 3000.0,
      heSo2: 0.05,
      batBuocThangThien: null,
      moTa:
        "Kéo dài thời lượng trạng thái Nộ Khí Xung Thiên: mỗi điểm cộng thêm 3000ms (3 giây), base mặc định 10000ms. Ở 80 điểm, thời lượng có thể kéo dài thêm tới 240000ms (4 phút).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:7909 (gán); Players.cs:69573 (tiêu thụ, set thời lượng status Nộ Khí).",
    },
    {
      index: 5,
      id: 26,
      ten: "Di hoa tiếp mộc",
      loai: "goc",
      heSo1: 0.4,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Chiêu hồi máu bản thân: cơ hội (roll 1-100, tối đa 32% ở 80 điểm) khi đánh trúng (cả đòn tay và chiêu, cả PvE lẫn PK) hồi lại 50% sát thương vừa gây ra thành máu cho bản thân.",
      trangThai: "BINH_THUONG",
      ghiChu: "PK tay: Players.cs:40629. PvE: Players.cs:42057. PK chiêu: Players.cs:45942.",
    },
    {
      index: 6,
      id: 182,
      ten: "Khí trầm đan điền",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Khí công phòng thủ thụ động: cộng cả vào HP tối đa lẫn % giảm sát thương chiêu, tối đa 40% ở 80 điểm. Field dùng chung nhiều nghề.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:7915 (gán); PlayersBes.cs:8537-8542 (tiêu thụ).",
    },
    {
      index: 7,
      id: 28,
      ten: "Nộ hải cuồng lan",
      loai: "goc",
      heSo1: 0.75,
      heSo2: 1.3,
      batBuocThangThien: null,
      moTa:
        "Chiêu đòn tay: cơ hội (roll 1-110 đòn tay, 1-100 chiêu; tối đa 54.5%-60% ở 80 điểm) nhân sát thương ×1.3. ĐÃ SỬA 2 lớp: (1) PK đòn tay — trước đây độc lập với Liên Hoàn Phi Vũ (idx2), có thể nổ cùng lúc tối đa dồn ×2.6; đã sửa bằng cờ loại trừ, Nộ Hải Cuồng Lan được xét trước. (2) PvE-chiêu và PK-chiêu — trước đây độc lập với Thăng Thiên Kinh Thiên Động Địa (id680) và Vô Kiên Bất Tồi/Thừa Thắng Truy Kích (idx9+10), 3 khối if có thể cộng dồn tối đa x2.63; đã đổi thành else-if loại trừ lẫn nhau.",
      trangThai: "DA_SUA",
      ghiChu:
        "PK tay: Players.cs ~39763-39780 (log VET_KIEM_NHCL). PvE tay: ~39222-39230. PvE chiêu: ~41253-41267. PK chiêu: ~44909-44930.",
    },
    {
      index: 8,
      id: 27,
      ten: "Hồi liễu thân pháp",
      loai: "goc",
      heSo1: 0.6,
      heSo2: 0.06,
      batBuocThangThien: null,
      moTa:
        "2 tác dụng dùng chung 1 cột điểm. (a) PHÒNG THỦ: khi bị đánh, cơ hội (roll theo cường hoá trang bị, tối đa 48 ở 80 điểm) VÔ HIỆU HOÀN TOÀN đòn vừa nhận (dame=0), như né toàn phần — nếu đang tung chiêu cấp≥5, còn cộng dồn stack 'Thiên Kiếm Phi Toái' cho Thăng Thiên Thiên Địa Đồng Thọ (id321). (b) CÔNG: hệ số 2 (0.06/điểm) nhân TRỰC TIẾP với số điểm đầu tư (khác đa số khí công khác dùng hệ số 2 như hằng số) để cộng vào % tăng sát thương chiêu vĩnh viễn, tối đa +480% ở 80 điểm — mẫu này KHÔNG phải lỗi riêng Kiếm (Đàm Hoa Liên dùng đúng mẫu này ở khí công tương ứng), nhưng +480% là biên độ rất lớn, nên đối chiếu log thực tế trước khi kết luận có phải nguồn góp phần 'dame Kiếm quá to' hay không.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs:7921-7922 (gán, phần CLVC dùng chung mẫu với DamHoaLien_HoiLieu_ThanPhap tại PlayersBes.cs:8278-8279). PK tay: Players.cs:40383. PK chiêu: Players.cs:45629-45636.",
    },
    {
      index: 9,
      id: 120,
      ten: "Vô kiên bất tồi",
      loai: "goc",
      heSo1: 0.2,
      heSo2: 1.5,
      batBuocThangThien: null,
      moTa:
        "Chiêu PvE/PK: dùng CHUNG một ngưỡng roll (1-100) với Thừa Thắng Truy Kích (idx10) — ngưỡng = tổng 2 khí công (tối đa 16+40=56 ở 80 điểm mỗi khí công, chưa vượt trần 100 nên chưa gây 'luôn 100%'). Khi trúng: nhân sát thương x(1.5 + ThuaThang_TruyKich×0.01). VẤN ĐỀ ĐÃ BIẾT (chưa sửa cấu trúc, chỉ đã sửa 1 phần): đây là 2 khí công RIÊNG BIỆT nhưng code cộng chung 1 ngưỡng roll thay vì roll độc lập — hiện KHÔNG gây bug '100% luôn trúng' vì tổng chưa vượt trần, nhưng là code-smell kiến trúc. Quyết định GIỮ NGUYÊN (không tách 2 roll như kế hoạch audit gốc đề xuất) vì nghi là combo có chủ đích — cần Admin xác nhận chính thức. Đã sửa riêng: nhánh PK trước đây THIẾU số hạng ×0.01 (chỉ có ở PvE), đã bổ sung để khớp.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PvE chiêu: Players.cs ~41263-41266. PK chiêu: Players.cs ~44923-44929 (đã sửa thêm số hạng ThuaThang_TruyKich×0.01). RÀ LẠI 03/09: ngưỡng gộp chưa vượt trần roll ở bất kỳ mức đầu tư nào hiện tại nên không gây behavior sai — coi là combo có chủ đích, không phải bug.",
    },
    {
      index: 10,
      id: 320,
      ten: "Thừa thắng truy kích",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Xem mô tả đầy đủ ở Vô Kiên Bất Tồi (idx9) — 2 khí công chia sẻ chung 1 ngưỡng roll, đang chờ Admin xác nhận có giữ nguyên hay không. Tự nó đóng góp: (1) phần cộng thêm vào ngưỡng roll chung (tối đa +40 ở 80 điểm), (2) phần khuếch đại hệ số nhân sát thương khi Vô Kiên Bất Tồi trúng (+điểm×0.01, tối đa +40%). Không có nhánh roll độc lập riêng.",
      trangThai: "BINH_THUONG",
      ghiChu: "Cùng vị trí code với idx9: PvE chiêu Players.cs ~41263-41266, PK chiêu Players.cs ~44923-44929. Xem lại kết luận ở idx9.",
    },
    {
      index: 11,
      id: 29,
      ten: "Trùng quan nhất nộ",
      loai: "goc",
      heSo1: 0.3,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Chiêu tăng tốc hồi Nộ Khí: base = 5.0 + điểm×0.3, roll 1-110, chỉ kích hoạt khi CHƯA ở trạng thái Nộ Khí. Khi trúng cộng thêm 0.5%×giá trị vào SP hiện tại. Áp dụng đồng nhất cả 4 đường đánh.",
      trangThai: "BINH_THUONG",
      ghiChu: "PK tay: Players.cs:40625-40627. PvE: 41028-41030, 42053-42055. PK chiêu: 45938-45940.",
    },
    {
      index: null,
      id: 25,
      ten: "Thăng thiên 1 - Hộ thân cương khí",
      loai: "thang_thien",
      heSo1: 0.4,
      heSo2: null,
      batBuocThangThien: 6,
      moTa:
        "Chiêu phòng thủ: base = 10.0 + điểm×0.4 (tối đa 42 ở 80 điểm), roll 1-110. Khi BỊ đánh trúng và roll thành công, giảm nửa sát thương vừa nhận. Áp dụng cả PK tay và PK chiêu.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8564-8566 (gán). PK tay: Players.cs:40378-40382. PK chiêu: 45624-45628.",
    },
    {
      index: null,
      id: 321,
      ten: "Thăng thiên 2 - Thiên địa đồng thọ",
      loai: "thang_thien",
      heSo1: 0.005,
      heSo2: null,
      batBuocThangThien: 7,
      moTa:
        "Cơ chế cộng dồn stack: mỗi khi Kiếm (hoặc Đàm Hoa Liên) NÉ ĐƯỢC một đòn tấn công trong PK — cả né chiêu cấp≥5 lẫn né THƯỜNG — được +1 stack 'Thiên Kiếm Phi Toái' (tối đa 3). Chiêu tiếp theo tung trúng đối phương được nhân sát thương x(1 + 0.005×điểm×số stack), tối đa +120% ở 3 stack, 80 điểm. Lịch sử (25/08, trước audit Kiếm 02/09): bản cũ chỉ cộng stack ở né-kỹ-năng-riêng, né THƯỜNG chưa bao giờ cộng stack vì hàm return sớm — đã sửa bổ sung.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs:8674-8676. Cộng stack: Players.cs ~44732-44756 (né thường, sửa 25/08). Trả thưởng: Players.cs ~45792-45797.",
    },
    {
      index: null,
      id: 322,
      ten: "Thăng thiên 3 - Hỏa phượng lâm triêu",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 8,
      moTa:
        "Hồi sinh khi tử vong: base = điểm×0.5, roll 1-100. Kiểm tra trong đoạn xử lý chung sau khi mất máu: nếu HP về ≤0 và roll trúng, HP được đặt lại thành 10 thay vì chết (miễn 1 lần tử vong).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8677-8681 (nhánh job2, gán). Tiêu thụ: Players.cs ~48871-48878.",
    },
    {
      index: null,
      id: 323,
      ten: "Thăng thiên 4 - Hồng nguyệt cuồng phong",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa:
        "Buff đồng đội diện rộng (yêu cầu Level>=140, Thăng Thiên>=9): base = điểm×0.5, roll 1-100 mỗi khi ra đòn trúng. Khi trúng cấp buff (+150 công, +150 phòng, 3 giây) cho mọi đồng minh cùng phe trong bán kính 300. Field dùng chung với nhiều nghề khác qua các mã khác.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8687-8689. Trigger: Players.cs:46331-46360.",
    },
    {
      index: null,
      id: 324,
      ten: "Thăng thiên 4 - Độc xà xuất động",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa:
        "Debuff khoá proc đối phương, cùng điều kiện cấp/level như Hồng Nguyệt Cuồng Phong. Khi trúng, gắn trạng thái 'Độc Xà Xuất Động' lên ĐỐI PHƯƠNG 3 giây, khiến hầu hết roll proc của chính đối phương gần như KHÔNG THỂ trúng trong thời gian đó — một dạng 'khoá kỹ năng' tạm thời.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8690-8692. Trigger: Players.cs:46094-46103. Kiểm tra: PlayersBes.cs:23583.",
    },
    {
      index: null,
      id: 571,
      ten: "Khí công bí cấp (Thăng Thiên 6 thức - Kiếm)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 11,
      moTa:
        "Field BachDocBatXam ('Bách Độc Bất Xâm'). base = điểm×0.1, roll 1-100, nhưng CHỈ được kiểm tra ở DUY NHẤT một vị trí — nhánh phòng thủ PK ĐÒN TAY. Khi trúng, code CHỈ gọi hiệu ứng hình ảnh — KHÔNG có bất kỳ dòng nào trừ sát thương, miễn độc, hồi máu hay đổi trạng thái. Không xuất hiện ở PK chiêu, PvE tay/chiêu. Kết luận: khí công bậc Thăng Thiên cao nhất này hiện KHÔNG có tác dụng cơ học thật, nhiều khả năng code chưa viết xong phần tác dụng thật.",
      trangThai: "CON_LOI_CHUA_SUA",
      ghiChu: "PlayersBes.cs:8872-8874. Tiêu thụ duy nhất: Players.cs:40387 (PK đòn tay, chỉ hiệu ứng hình). PHÁT HIỆN MỚI 09/2026.",
    },
    {
      index: null,
      id: 680,
      ten: "[Kiếm] Khí công bí cấp thư (Thăng Thiên 5 thức - Kinh Thiên Động Địa)",
      loai: "thang_thien",
      heSo1: 0.6,
      heSo2: null,
      batBuocThangThien: 10,
      moTa:
        "Ultimate riêng của Kiếm, field ThangThien_5_KinhThienDongDia. base = điểm×0.6 (tối đa 48 ở 80 điểm), roll 1-100. Khi trúng: nhân sát thương chiêu lên hằng số CỐ ĐỊNH ×1.35 (điểm đầu tư chỉ quyết định % cơ hội trúng, không quyết định độ mạnh). ĐÃ SỬA — 1 trong 3 nhánh của bug '3-proc không loại trừ': trước đây là 1 trong 3 khối if độc lập cùng Nộ Hải Cuồng Lan (idx7) và Vô Kiên Bất Tồi (idx9), có thể cộng dồn (tối đa x2.63 tổng). Đã đổi thành else-if loại trừ lẫn nhau, xét ưu tiên THỨ NHÌ (sau Nộ Hải Cuồng Lan, trước Vô Kiên Bất Tồi/Thừa Thắng Truy Kích).",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs:8763-8765. PvE chiêu: Players.cs ~41245-41273 (else-if). PK chiêu: ~44909-44931 (else-if).",
    },
  ],
};
