import type { NgheData } from "./types";

export const JOB_09_DAM_HOA_LIEN: NgheData = {
  job: 9,
  tenNghe: "Đàm Hoa Liên",
  khiCong: [
    {
      index: 0,
      id: 270,
      ten: "Trường hồng quán nhật",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng công kích đòn tay, công thức dùng khuôn shared engine-wide (giống Kiếm/Cầm Sư/Quyền Sư).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case9 idx0 (~8237-8246).",
    },
    {
      index: 1,
      id: 271,
      ten: "Bách biến thần hành",
      loai: "goc",
      heSo1: 0.1,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng né tránh, field né tránh dùng chung toàn engine.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case9 idx1 (~8247-8249).",
    },
    {
      index: 2,
      id: 272,
      ten: "Tân _ liên hoàn phi vũ",
      loai: "goc",
      heSo1: 1.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Không nơi nào trong Players.cs/PlayersBes.cs đọc field này ngoài gán+reset — khí công 'chết', đầu điểm không có tác dụng gì.",
      trangThai: "CHET_HOAN_TOAN",
      ghiChu: "PlayersBes.cs case9 idx2 (~8250-8255): DamHoaLien_LienHoanPhiVu. Chưa rõ ý đồ thiết kế gốc, chưa tự chế công thức mới.",
    },
    {
      index: 3,
      id: 273,
      ten: "Chiêu thức tân pháp",
      loai: "goc",
      heSo1: 0.2,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Điều khiển thời lượng đóng băng (trạng thái 28, không di chuyển được) khi tung combo 'Hấp Hồn Đại Pháp' (VoCong 2000401, cooldown 15s). Cố định 3 giây mọi mức đầu tư (theo đúng hằng số gốc trong code, Admin xác nhận 03/09).",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs case9 idx3 (~8256-8261). BUG PHÁT HIỆN 03/09 (từ đợt sửa 'bổ sung num2' trước đó): field = 1000.0×điểm×hệSố, nơi tiêu thụ (Players.cs ~41893 PvE, ~42499 PK) còn nhân thêm ×20 (100/5) — nhân chồng 2 lớp khiến thời lượng thực tế lên tới hàng trăm giây (323s ở 80 điểm) trong khi skill cooldown chỉ 15s — combo lock gần như vĩnh viễn. Không tìm được mô tả gốc trong DB (FLD_DES rỗng) để đối chiếu số chính xác; hằng số '+3000' có sẵn trong code (độc lập điểm đầu tư) là căn cứ duy nhất có thật, Admin xác nhận dùng 3000ms cố định, bỏ hẳn phần nhân theo điểm. Đã nạp K2 .266.",
    },
    {
      index: 4,
      id: 274,
      ten: "Cuồng phong vạn phá",
      loai: "goc",
      heSo1: 3000.0,
      heSo2: 0.05,
      batBuocThangThien: null,
      moTa: "Kéo dài thời gian buff Nộ Khí, field dùng chung ~8 nghề.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs ~69573.",
    },
    {
      index: 5,
      id: 275,
      ten: "Hộ thân cương khí",
      loai: "goc",
      heSo1: 0.4,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Proc khi bị tấn công, trần tối đa 38-42, dưới 100 nên chưa vượt trần RNG.Next(1,100).",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs ~40425 (chiêu PvE), ~45699 (chiêu PK, trừ Giam_Tac_dung_Cua_Khi_Cong).",
    },
    {
      index: 6,
      id: 189,
      ten: "Khí trầm đan điền",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Buff HP/DEF phổ quát, tính ngay trong UpdateKhiCong.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~8537-8543.",
    },
    {
      index: 7,
      id: 276,
      ten: "Di hoa tiếp mộc",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Proc trần tối đa 80, dưới 100 nên chưa vượt trần.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs ~40641/41044/42076/45958.",
    },
    {
      index: 8,
      id: 277,
      ten: "Tung hoành vô song",
      loai: "goc",
      heSo1: 0.3,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Điều khiển tỉ lệ nối chuỗi combo đòn tay job9. 2 nhánh roll, trần tối đa đều dưới ngưỡng RNG tương ứng.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs ~71098-71107, ~71340-71349.",
    },
    {
      index: 9,
      id: 278,
      ten: "Hồi liễu thân pháp",
      loai: "goc",
      heSo1: 0.6,
      heSo2: 0.006,
      batBuocThangThien: null,
      moTa: "Slot 1: proc hồi máu. Slot 2: cộng vào CLVC dame chung (field dùng chung toàn engine, đã xác nhận qua log VET_DAME_PK).",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs ~40430/45704.",
    },
    {
      index: 10,
      id: 279,
      ten: "Nộ hải cuồng lan",
      loai: "goc",
      heSo1: 0.4,
      heSo2: 1.2,
      batBuocThangThien: null,
      moTa: "Tỉ lệ proc scale theo điểm, hệ số nhân dame cố định (không scale) — thiết kế có chủ ý, không phải lỗi.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "Players.cs ~39315 (PK tay), ~39910 (PvE tay), ~41830 (PvE chiêu), ~45474 (PK chiêu). Có cộng dồn +10.0 tại ~42788-42790 (hiệu ứng item/buff riêng, thuộc rủi ro chung buff đồng đội).",
    },
    {
      index: 11,
      id: 280,
      ten: "Trùng quan nhất nộ",
      loai: "goc",
      heSo1: 0.35,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Proc cộng thêm Nộ Khí, trần tối đa 29.5-33, dưới 110 nên chưa vượt trần.",
      trangThai: "BINH_THUONG",
      ghiChu: "Players.cs ~40637/41040/42071/45954.",
    },
    {
      index: null,
      id: 321,
      ten: "Thăng thiên 2 - Thiên địa đồng thọ",
      loai: "thang_thien",
      heSo1: 0.005,
      heSo2: null,
      batBuocThangThien: 7,
      moTa:
        "Ghi vào field mang tiền tố 'KIEM_' (di sản từ Kiếm) nhưng điều kiện tiêu thụ là (Player_Job==2 || Player_Job==9), nên Đàm Hoa Liên VẪN được hưởng đúng — chỉ tên field gây hiểu lầm, không phải lỗi chức năng. Nhân dame theo số lần né 'Thiên Kiếm Phi Toái' dồn (tối đa 3 lần rồi reset).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~8674. Players.cs ~45792-45796.",
    },
    {
      index: null,
      id: 322,
      ten: "Thăng thiên 3 - Hỏa phượng lâm triêu",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 8,
      moTa: "Khi HP<=0, roll trúng thì hồi sinh tại chỗ với 10 HP (tự cứu mạng).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~8677-8686 (nhánh job9). Players.cs ~48914-48918.",
    },
    {
      index: null,
      id: 578,
      ten: "Khí công bí cấp (Thăng Thiên 6 thức - Đàm Hoa Liên)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 11,
      moTa: "CHẾT HOÀN TOÀN: grep toàn repo chỉ thấy field DienQuangTrieuLo ở nơi reset và gán — không có nơi tiêu thụ nào. Đầu điểm hoàn toàn vô tác dụng.",
      trangThai: "CON_LOI_CHUA_SUA",
      ghiChu:
        "PlayersBes.cs ~8895-8897. Cùng mẫu bug 'CHET_HOAN_TOAN' đã ghi nhận ở nghề khác. Chưa rõ ý đồ thiết kế gốc, chưa tự chế công thức, cần Admin xác nhận.",
    },
    {
      index: null,
      id: 687,
      ten: "[Đàm hoa linh] Khí công bí cấp thư (Kinh đào hãi lãng, Thăng Thiên 5 thức)",
      loai: "thang_thien",
      heSo1: 0.3,
      heSo2: null,
      batBuocThangThien: 10,
      moTa:
        "Giảm dame nhận vào khi bị phản đòn (Đao phản đòn/Cùng Đồ Mạt Lộ). BUG CẤU TRÚC: điều kiện 'DiNhuKhacCuong>0.0' (khí công 700) là BẮT BUỘC đứng trước — nếu chỉ đầu 687 mà KHÔNG đầu 700, nhánh không bao giờ chạy dù roll gì, 687 đầu độc lập VÔ DỤNG HOÀN TOÀN. Ngay cả khi đã đầu cả 2, giá trị 687 chỉ cộng vào NGƯỠNG ROLL (tỉ lệ trúng) chứ không xuất hiện trong công thức mức giảm dame — tự nó không có hiệu ứng riêng, chỉ làm TĂNG TỈ LỆ PROC hộ cho 700.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs ~8784-8786. 6 vị trí: Players.cs ~40300, 40347, 40434, 45724, 48796, 48837. RÀ LẠI 03/09: chưa vượt trần RNG (max ~49-56/110) nên không gây behavior sai hiện tại — cùng kết luận như Kiếm idx9/10 (kiến trúc combo có chủ đích, không phải bug).",
    },
    {
      index: null,
      id: 700,
      ten: "Thăng thiên 3 - Dĩ nhu khắc cương",
      loai: "thang_thien",
      heSo1: 0.4,
      heSo2: null,
      batBuocThangThien: 8,
      moTa:
        "Là 'khí công chủ' trong cặp combo với 687 — xem chi tiết ở mục 687. Giảm dame khi bị phản đòn; điểm đầu vào 687 cộng thêm vào ngưỡng roll của chính khí công này (không đổi mức giảm dame).",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs ~8796-8798 (tên field nội bộ 'ThangThien_1' dù tên hiển thị là 'thăng thiên 3' — chỉ lệch tên biến). 6 vị trí: Players.cs ~40300-40304, 40347-40351, 40434-40437, 45724-45727, 48796-48799, 48837-48840. Xem lại kết luận ở id687.",
    },
    {
      index: null,
      id: 701,
      ten: "Thăng thiên 4 - Trường hồng quán thiên",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Proc kích hoạt hiệu ứng 'thăng thiên 4' (choáng/debuff đối thủ), field dùng chung với HanBaoQuan (id603).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~8799-8801. Players.cs ~46439.",
    },
    {
      index: null,
      id: 702,
      ten: "Thăng thiên 4 - Ai hồng biến dã",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "AoE giảm 0.15 giới hạn HP cao nhất cho đối thủ trong phạm vi 300, field dùng chung với HanBaoQuan (id604).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs ~8802-8804. Players.cs ~46105-46153 (có gate riêng cho map TLC/Môn Chiến).",
    },
  ],
};
