import type { NgheData } from "./types";

export const JOB_12_TU_HAO: NgheData = {
  job: 12,
  tenNghe: "Tử Hào",
  khiCong: [
    {
      index: 0,
      id: 281,
      ten: "Kim chung cương khí",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng thẳng vào phòng ngự cộng thêm từ khí công. Không qua roll, field chung nhiều nghề.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case0 job12 (~8392-8394).",
    },
    {
      index: 1,
      id: 282,
      ten: "Vận khí liệu thương",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Field này thuộc về nghề Thương (job3): nơi tiêu thụ duy nhất chỉ mở khi Player_Job==3. Tử Hào đầu điểm nhưng field không bao giờ được đọc — khí công CHẾT hoàn toàn với Tử Hào. Y hệt bug của Quyền Sư idx1 cùng field.",
      trangThai: "CON_LOI_CHUA_SUA",
      ghiChu:
        "PlayersBes.cs case1 job12 (~8395-8401, có comment giải thích). Gate tại AddBlood() Player_Job==3. Không mở gate vì Tử Hào ĐÃ CÓ đường hồi máu khác qua Thăng Thiên — mở gate sẽ tạo double-dip, cần Admin quyết định thiết kế.",
    },
    {
      index: 2,
      id: 283,
      ten: "Liên hoàn phi vũ",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Field dùng CHUNG với nghề Thương (job3), bị gate Player_Job==3 tại nơi tiêu thụ. Khác Vận Khí Liệu Thương: Tử Hào ĐÃ CÓ sẵn cơ chế đòn tay RIÊNG (gộp chung job 8/9/10, bảng xác suất hoạt ảnh cố định khác hẳn). Mở gate job3 sẽ THAY THẾ HOÀN TOÀN cơ chế hiện tại thay vì cộng thêm.",
      trangThai: "CON_LOI_CHUA_SUA",
      ghiChu: "PlayersBes.cs case2 job12 (~8402-8411). Cần Admin quyết định thiết kế trước khi đụng.",
    },
    {
      index: 3,
      id: 284,
      ten: "Hoành luyện thái bảo",
      loai: "goc",
      heSo1: 8.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng thẳng HP tối đa, thụ động, field dùng chung nhiều nghề.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case3 job12 (~8412-8414).",
    },
    {
      index: 4,
      id: 285,
      ten: "Cuồng phong vạn phá",
      loai: "goc",
      heSo1: 3000.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Kéo dài thời gian Nộ Khí Xung Thiên. Tử Hào rơi vào nhánh else dùng chung (không có công thức riêng như job3/10/11) nên chỉ nhận +20% công/thủ cố định, phần đầu tư CHỈ kéo dài thời lượng buff (tối đa +240s ở 80 điểm).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case4 job12. Players.cs~69573, nhánh else~69608-69615.",
    },
    {
      index: 5,
      id: 287,
      ten: "Chân vũ tuyệt kích",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 1.3,
      batBuocThangThien: null,
      moTa: "2 hệ số đều sống: hệ số1 = tỉ lệ % proc, hệ số2 = số nhân sát thương cố định khi trúng (không nhân theo điểm). Field dùng chung với Đao/Đại Phu/HanBaoQuan.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case5 job12 (~8418-8420). Players.cs PvE-chiêu ~41929/41932, PK-chiêu ~45570/45573.",
    },
    {
      index: 6,
      id: 192,
      ten: "Khí trầm đan điền",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Field dùng chung nhiều nghề (share với Thần Nữ case5) — cộng HP và ULPT.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case6 job12 (~8421-8423); tiêu thụ chung PlayersBes.cs~8537-8543.",
    },
    {
      index: 7,
      id: 286,
      ten: "Lưu tinh mạn thiên",
      loai: "goc",
      heSo1: 2.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "🟠 Bug NẶNG THỨ 2 toàn đợt audit — 2 phần: (1) Lỗi thứ tự if/else: công thức gốc kiểm tra level từ THẤP lên CAO khiến nhánh '>=6' luôn chặn trước, các mốc level 7/8/9 (endgame) không bao giờ đạt tới, kẹt vĩnh viễn ở +20. ĐÃ SỬA: sắp lại từ CAO xuống THẤP. (2) 🔴 Lỗi tỉ lệ proc vượt trần: giá trị (có thể tới ~180 do lỗi #1) CỘNG THẲNG với khí công Thăng Thiên 'Phá Không Trụy Tinh' (id690, tối đa 81) KHÔNG có clamp — chỉ cần ~40/80 điểm là tổng đã chạm 100, proc buff sát thương (×1.2-×2.0) LUÔN LUÔN đúng. RẤT CÓ THỂ là lý do DAME_PK_JOB_12_BONUS (Gsconfig) từng bị hạ xuống 0.90 (duy nhất dưới 1.0) để vá tạm. ĐÃ SỬA: bọc Math.Min(tổng, 99.0).",
      trangThai: "DA_SUA",
      ghiChu:
        "Players.cs ~41895-41900 (PvE), ~45540-45545 (PK). Log VET_TUHAO_LTMT. Cơ chế đầy đủ khi proc trúng: roll lồng chọn 1 trong 2 nhánh loại trừ nhau — Nhược Điểm Kích Phá (idx10, ×1.2/×1.8) hoặc Vân Sơn Công (id664, ×2.0).",
    },
    {
      index: 8,
      id: 288,
      ten: "Càn khôn na di",
      loai: "goc",
      heSo1: 0.015,
      heSo2: 0.04,
      batBuocThangThien: null,
      moTa: "Hệ số1: % tăng sát thương chung, sống bình thường qua TotalSkillDamage. Hệ số2: nhân thêm THUONG_LienHoanPhiVu (idx2) — nhưng field đó CHẾT với Tử Hào (chỉ đọc khi Player_Job==3), nên phần hệ số2 tính xong rồi bỏ, không sập, chỉ là phép tính thừa vô hại.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case8 job12 (~8461-8464). Gắn liền quyết định của idx2.",
    },
    {
      index: 9,
      id: 289,
      ten: "Chuyển công vi thủ",
      loai: "goc",
      heSo1: 0.004,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Khí công phòng thủ, rất nhỏ (max ~5.3% ở 80 điểm): khi bị đánh bằng chiêu PK, proc trúng thì cộng công lực thành phòng thủ. Chỉ có ở PK-chiêu, khớp đúng khuôn 2 nghề song sinh (Thương/Quyền Sư), không phải thiếu sót.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case9 job12 (~8465-8467). Players.cs PK-chiêu ~44607.",
    },
    {
      index: 10,
      id: 290,
      ten: "Nhược điểm kích phá",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Không phải proc độc lập — lồng bên trong nhánh khi Lưu Tinh Mãn Thiên (idx7) đã proc: roll riêng, trúng nhân ×1.2 (hoặc ×1.8 nếu đồng thời trúng Sát Tinh Quang Phù id663). Trần lý thuyết 90 vẫn dưới trần roll 100, không nguy cơ luôn-đúng.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case10 job12 (~8468-8470). Players.cs PvE-chiêu ~41906, PK-chiêu ~45550.",
    },
    {
      index: 11,
      id: 291,
      ten: "Lao bất khả phá",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Khí công phòng thủ trên người bị tấn công (chiêu PK): proc trúng thì cấp trạng thái bất thường, tác động lên tầng tính thuộc tính trang bị. Chỉ ở chiêu PK, khớp khuôn idx9.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case11 job12 (~8471-8473). Players.cs PK-chiêu ~44580.",
    },
    {
      index: null,
      id: 662,
      ten: "Thăng Thiên 1 — Lăng kình thối lệ",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 6,
      moTa: "Proc cấp trạng thái bất thường (3 giây) cho bản thân khi bị tấn công bằng chiêu PK, tác động qua tầng tính thuộc tính trang bị, giống idx11.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case662 (~8745-8747). Players.cs PvE-chiêu ~41120, PK-chiêu ~44587.",
    },
    {
      index: null,
      id: 663,
      ten: "Thăng Thiên 2 — Sát tinh quang phù",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 7,
      moTa: "Không phải proc độc lập — so sánh bên trong nhánh Nhược Điểm Kích Phá (idx10) đã trúng: đạt thì nhân ×1.8 thay vì ×1.2 mặc định.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case663 (~8748-8750). Players.cs PvE-chiêu ~41908/41910, PK-chiêu ~45553/45555.",
    },
    {
      index: null,
      id: 664,
      ten: "Thăng Thiên 3 — Vân Sơn Công",
      loai: "thang_thien",
      heSo1: 1.0,
      heSo2: null,
      batBuocThangThien: 8,
      moTa: "Nhánh THAY THẾ (else if) khi Nhược Điểm Kích Phá KHÔNG trúng, vẫn trong phạm vi Lưu Tinh Mãn Thiên đã proc: roll riêng, trúng nhân ×2.0 — mức nhân mạnh nhất trong 3 lựa chọn.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case664 (~8751-8753). Trần max 80, dưới trần roll 100, an toàn.",
    },
    {
      index: null,
      id: 665,
      ten: "Thăng Thiên 4 — Độc xà xuất động",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Field dùng chung 'chọn 1 trong 4 Thăng Thiên bậc 4' của nhiều nghề. Proc gắn DoT độc 3 giây lên mục tiêu, hàm chạy chung không phân biệt PvE/PK.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case665 (~8754-8756). AscensionFourQigongTrigger Players.cs~46095-46103.",
    },
    {
      index: null,
      id: 666,
      ten: "Thăng Thiên 4 — Hồng nguyệt cuồng phong",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Cùng nhóm 'chọn 1 trong 4' như id665. Roll độc lập, không cộng dồn với field nào khác.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case666 (~8757-8759). Players.cs~46333.",
    },
    {
      index: null,
      id: 690,
      ten: "[Lư Phong Lang] Khí công bí cấp thư (Phá Không Trụy Tinh, Thăng Thiên 5 thức)",
      loai: "thang_thien",
      heSo1: 1.0,
      heSo2: null,
      batBuocThangThien: 10,
      moTa:
        "🟠 Nửa còn lại của bug nặng thứ 2 toàn đợt audit (xem đầy đủ ở Lưu Tinh Mãn Thiên idx7 — 2 khí công dùng chung 1 công thức proc). Field này CỘNG THẲNG với LuuTinhManThien mà KHÔNG có clamp trong bản gốc — chỉ cần ~40 điểm Lưu Tinh Mãn Thiên là tổng vượt 100, proc LUÔN đúng.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs case690 (~8793-8795). ĐÃ SỬA: bọc Math.Min(tổng, 99.0) tại cả PvE-chiêu và PK-chiêu. Log VET_TUHAO_LTMT.",
    },
    {
      index: null,
      id: 581,
      ten: "Khí công bí cấp (Thăng Thiên 6 thức - Tử Hào)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 11,
      moTa:
        "Field PhanDanVoHieu — giảm % sát thương PHẢN ĐÒN mà Tử Hào phải nhận lại khi tấn công đối thủ có kỹ năng 'phản sát thương' (Đao Tữ Lưỡng Thiên Kim, Đàm Hoa Liên Dĩ Nhu Khắc Cương...). Gate đúng job==12, roll trúng thì giảm lượng sát thương phản lại theo % giá trị khí công.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs case581 (~8912-8914). Tiêu thụ 4 vị trí: Players.cs ~40311/40358 (PK-tay), ~48891/48932 (xử lý phản đòn). Đã đọc code xác nhận hoạt động đúng thiết kế, không phát hiện lỗi.",
    },
  ],
};
