import type { NgheData } from "./types";

export const JOB_10_QUYEN_SU: NgheData = {
  job: 10,
  tenNghe: "Quyền Sư",
  khiCong: [
    {
      index: 0,
      id: 550,
      ten: "Cuồng thần hàng thế",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Hồi thêm SP mỗi tick khi KHÔNG ở Nộ Khí Xung Thiên.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8292-8294. Players.cs:48707-48717.",
    },
    {
      index: 1,
      id: 551,
      ten: "Vận khí liệu thương",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Đầu điểm vào field THUONG_VanKhi_LieuThuong (về tên gọi 'thuộc' nghề Thương/job3), nhưng nơi tiêu thụ duy nhất chỉ mở gate cho Player_Job==3.",
      trangThai: "CON_LOI_CHUA_SUA",
      ghiChu:
        "PlayersBes.cs:8296-8304 (đã có comment 02/09 giải thích). Gate thật ở AddBlood() PlayersBes.cs:25355-25358 chỉ if(Player_Job==3). Quyền Sư (job!=3) ĐÃ có đường hồi máu riêng qua Thăng Thiên ThangThien_1_KhiCong_VanKhi_LieuThuong (AddBlood() dòng 25359-25362) — mở gate cũ sẽ tạo buff kép (2 nguồn hồi máu cộng dồn), là thay đổi cân bằng mới. Cần Admin quyết định thiết kế trước khi sửa.",
    },
    {
      index: 2,
      id: 552,
      ten: "Lực phách hoa sơn",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.01,
      batBuocThangThien: null,
      moTa: "Cộng thêm công kích phẳng, công thức chung nhiều nghề.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8305-8314. Hệ số 2 không thấy dùng riêng cho case này — có thể cột DB dư.",
    },
    {
      index: 3,
      id: 553,
      ten: "Cuồng phong vạn phá",
      loai: "goc",
      heSo1: 3000.0,
      heSo2: 0.15,
      batBuocThangThien: null,
      moTa: "Field CuongPhong_VanPha dùng chung nhiều nghề — cộng thêm thời lượng buff Nộ Khí Xung Thiên.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8315-8317. Players.cs:69573.",
    },
    {
      index: 4,
      id: 558,
      ten: "Linh giáp hộ thân",
      loai: "goc",
      heSo1: 0.003,
      heSo2: 3.0,
      batBuocThangThien: null,
      moTa: "Cộng thêm lực phòng ngự võ công, dùng trực tiếp hệ số 2 (3.0), không dùng hệ số 1 (quy ước chung nhóm field ULPT, không riêng job10).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8318-8320. Cùng khuôn mẫu Thương idx11, Cầm Sư idx3 — chủ ý thiết kế, không phải bug.",
    },
    {
      index: 5,
      id: 559,
      ten: "Ma xử thành châm",
      loai: "goc",
      heSo1: 0.005,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cộng thêm % sát thương khi đang trong trạng thái combo (2-5), trừ 2 chiêu 3000101/3000105.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8321-8323. Players.cs:41841-41844 (chiêu PvE), 45479-45482 (chiêu PK).",
    },
    {
      index: 6,
      id: 190,
      ten: "Khí trầm đan điền",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Field dùng chung mọi nghề — cộng thêm HP và ULPT theo % phòng ngự.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8324-8326; PlayersBes.cs:8537-8543.",
    },
    {
      index: 7,
      id: 556,
      ten: "Thủy hỏa nhất thể",
      loai: "goc",
      heSo1: 0.6,
      heSo2: 0.5,
      batBuocThangThien: null,
      moTa: "Nhân thêm % sát thương khi ra chiêu (không áp cho đòn tay).",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs:8327-8329. Players.cs:41837-41840 (chiêu PvE, AttackComputing). Chưa thấy nhánh tương ứng trong chiêu PK — cần đối chiếu thêm nếu cần xác nhận có ở PK.",
    },
    {
      index: 8,
      id: 554,
      ten: "Kim cương bất phôi",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Khi bị trúng đòn > nửa HP hiện tại, có cơ hội (roll 1-110) giảm sát thương đó. Hoạt động cả đòn tay PK và chiêu PK.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8330-8332. Players.cs:40440-40446 (đòn tay), 45730-45736 (chiêu). Base tối đa chỉ 90, không tự proc.",
    },
    {
      index: 9,
      id: 555,
      ten: "Chuyển công vi thủ",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Khi bị tấn công, có cơ hội phản đòn gây thêm sát thương. Hoạt động cả đòn tay PK, chiêu PK và khi bị quái đánh (PvE).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8333-8335. Players.cs:39675-39678, 44602; NpcClass.cs:1368-1372.",
    },
    {
      index: 10,
      id: 557,
      ten: "Hội tâm nhất kích",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 2.0,
      batBuocThangThien: null,
      moTa:
        "Chỉ khi RA CHIÊU (không áp đòn tay, cả PK/PvE): cơ hội nhân thêm sát thương +30% nếu đang combo, +15% nếu chiêu thường. Cộng dồn thêm bởi Thăng Thiên 3 (Tinh ích cầu tinh, id563).",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs:8336-8338. Players.cs:41845-41862 (PvE), 45483-45500 (PK); khởi tạo UyLuc Players.cs:69592-69595. Hệ số 2 (2.0) không thấy được gọi ở đâu — dữ liệu DB dư, không ảnh hưởng chức năng. Chỉ áp cho chiêu là chủ ý thiết kế nhất quán.",
    },
    {
      index: 11,
      id: 560,
      ten: "Mạt nhật cuồng vũ",
      loai: "goc",
      heSo1: 0.005,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Khi kích hoạt Nộ Khí Xung Thiên, cộng thêm % tăng công kích và phòng ngự.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8339-8341. Players.cs:69585-69591.",
    },
    {
      index: null,
      id: 561,
      ten: "Thăng thiên 2 đoạt mệnh liên hoàn",
      loai: "thang_thien",
      heSo1: 0.3,
      heSo2: null,
      batBuocThangThien: 7,
      moTa: "Chỉ khi ra chiêu ở trạng thái combo đặc biệt (cùng điều kiện Hội Tâm Nhất Kích) mới có cơ hội nhân thêm ×1.4 sát thương. Không áp đòn tay, nhất quán chủ ý thiết kế.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8853-8855. Players.cs:41852-41856, 45490-45494.",
    },
    {
      index: null,
      id: 562,
      ten: "Thăng thiên 1 điện quang thạch hỏa",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 6,
      moTa: "Khi đối thủ (Kiếm/Ninja/Đàm Hoa Liên) né đòn thành công nhờ khí công né riêng, Quyền Sư có cơ hội gây choáng lên đối thủ dù họ đã né được.",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs:8856-8858. Có mặt trong chiêu PK (Players.cs 45636-45645/45683-45692/45711-45720). ĐÃ SỬA 03/09: đòn tay PK có đúng 3 nhánh né tương tự (Kiếm/Ninja/Đàm Hoa Liên, Players.cs ~40389/40412/40436) nhưng trước đây không có nhánh choáng này đi kèm — nay đã bổ sung 3 khối (mỗi khối áp choáng 3000ms lên value3 khi Player_Job==10 và có điểm khí công) khớp cấu trúc chiêu PK.",
    },
    {
      index: null,
      id: 563,
      ten: "Thăng thiên 3 tinh ích cầu tinh",
      loai: "thang_thien",
      heSo1: 0.005,
      heSo2: null,
      batBuocThangThien: 8,
      moTa: "Không có hiệu ứng độc lập — chỉ cộng dồn thêm vào 2 mốc UyLuc (0.3 và 0.15) của idx10 'Hội tâm nhất kích'.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8859-8861. Players.cs:69593,69595.",
    },
    {
      index: null,
      id: 564,
      ten: "Thăng thiên 4 hồng nguyệt cuồng phong",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Field dùng chung 'Thăng Thiên 4' của nhiều nghề — khi trúng đòn (mọi loại) có cơ hội gây debuff lên mục tiêu qua hàm dùng chung.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8862-8864. Players.cs:46333, gọi từ cả 4 đường tay/chiêu/PvE/PK.",
    },
    {
      index: null,
      id: 565,
      ten: "Thăng thiên 4 độc xà xuất động",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Cùng nhóm 'Thăng Thiên 4' dùng chung như id564 — khi trúng đòn có cơ hội gây debuff qua AscensionFourQigongTrigger.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8865-8867. Players.cs:46095.",
    },
    {
      index: null,
      id: 579,
      ten: "Khí công bí cấp (Thăng Thiên 6 thức - QS)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 11,
      moTa: "Đầu điểm được, giá trị được tính nhưng KHÔNG có bất kỳ hiệu ứng gameplay nào — khí công 'chết' hoàn toàn với Quyền Sư.",
      trangThai: "CHET_HOAN_TOAN",
      ghiChu:
        "PlayersBes.cs:6433 (reset), 8898-8900 (gán). Grep toàn repo cho 'VoChuongVoNgai' KHÔNG tìm thấy nơi đọc nào. Khác các field 'Thăng Thiên 6' tự-áp-dụng của Đao/Ninja/Cầm Sư (cộng thẳng HP/PhongNgu ngay trong PlayersBes.cs), field job10 hoàn toàn mồ côi. Cần Admin/thiết kế xác nhận trước khi viết công thức tiêu thụ mới.",
    },
    {
      index: null,
      id: 688,
      ten: "[Cách đấu gia] Khí công bí cấp thư (Bất tử chi khu, Thăng Thiên 6 thức)",
      loai: "thang_thien",
      heSo1: 0.7,
      heSo2: null,
      batBuocThangThien: 10,
      moTa: "'Bất tử chi khu' — khi bị trúng đòn, có cơ hội né HOÀN TOÀN sát thương đó (đưa về 0).",
      trangThai: "DA_SUA",
      ghiChu:
        "PlayersBes.cs:8787-8789. Hoạt động đúng ở chiêu PK (Players.cs:45737-45741) và ở đòn quái tấn công người chơi (NpcClass.cs:1378-1382). ĐÃ SỬA 03/09: đòn tay PK (Players.cs ~40446-40460) trước đây chỉ có nhánh Kim Cương Bất Hoại (554), thiếu hẳn nhánh này khiến khí công 'bất tử' bậc 10 vô dụng khi bị đánh tay trong PK — nay đã bổ sung khối negate-toàn-phần ngay sau Kim Cương Bất Hoại, khớp hành vi chiêu PK.",
    },
  ],
};
