import type { NgheData } from "./types";

// job=13 LÀ Thần Nữ thật (field ThanNu_*, DB có 2 dòng skill hậu tố "(Thần nữ)"). job=8 KHÔNG
// PHẢI Thần Nữ (tên nội bộ "HanBaoQuan") — giả định sai đã tồn tại nhiều phiên trước, đã đính chính.
export const JOB_13_THAN_NU: NgheData = {
  job: 13,
  tenNghe: "Thần Nữ",
  khiCong: [
    {
      index: 0,
      id: 450,
      ten: "Vận khí hành tâm",
      loai: "goc",
      heSo1: 0.04,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Tăng lượng MP hồi được từ đan dược/thuốc hồi MP (không phải hồi tự nhiên). Tối đa +320% lượng MP nhận từ 1 lần dùng thuốc.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "Field ThanNu_VanKhiHanhTam. Gán PlayersBes.cs~8480. Tiêu thụ DUY NHẤT tại PlayersBes.cs:25385 (hàm MagicPlus) — không nằm trong Players.cs nên dễ bị đánh giá nhầm là chết nếu chỉ grep Players.cs.",
    },
    {
      index: 1,
      id: 451,
      ten: "Thái cực tâm pháp",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Giảm phí MP khi dùng chiêu thức, tối đa giảm 80% ở 80 điểm. Cùng mẫu với Đại Phu/Cầm Sư nhưng hệ số gốc=1.0 tự nhiên chặn ở 80%, KHÔNG bị lỗi tràn trần như Cầm Sư (hệ số 1.2, đã phải vá clamp riêng).",
      trangThai: "BINH_THUONG",
      ghiChu: "Field ThanNu_ThaiCucTamPhap. Gán PlayersBes.cs~8483. Players.cs:46637.",
    },
    {
      index: 2,
      id: 452,
      ten: "Thần lực kích phát",
      loai: "goc",
      heSo1: 0.005,
      heSo2: 5.0,
      batBuocThangThien: null,
      moTa:
        "2 thành phần. (1) Cổng mở cho proc 'Thần Lực Kích Phát' — xác suất proc thật ra CỐ ĐỊNH 10% (không tăng theo điểm đầu tư!), khi trúng nhân dame đơn mục tiêu x(1.15+idx3); đồng thời giá trị còn dùng trực tiếp làm hệ số nhân sát thương trong nhánh tính lại sát thương AoE/proc đặc biệt (tối đa +40% dame). (2) Thành phần 'PT_QUAI' (hệ số 2 = 50+điểm×5, tối đa 450): CHỈ cộng giáp chống lại đòn quái (PvE), không có tác dụng PK.",
      trangThai: "CON_LOI_CHUA_SUA",
      ghiChu:
        "Field ThanNu_ThanLucKichPhat + ThanNu_ThanLucKichPhat_PT_QUAI. Gán PlayersBes.cs:8486-8487. Cổng proc: Players.cs:41942 (PvE)/45580 (PK). Dame trực tiếp: Players.cs:46889. PT_QUAI: NpcClass.cs:1310. Số mục tiêu AoE khi proc trúng nay đã cố định — xem entry idx3.",
    },
    {
      index: 3,
      id: 453,
      ten: "Sát tinh nghĩa khí",
      loai: "goc",
      heSo1: 0.002,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "3 hiệu ứng dùng chung 1 field: (1) proc riêng 'Trung Nghĩa Sát' (skill đơn mục tiêu) xác suất CỐ ĐỊNH 10%, khi trúng nhân dame x(1.35+giá trị), tối đa x1.51 ở 80 điểm. (2) Nới bán kính tìm mục tiêu AoE PvE thêm (điểm×0.002×100), tối đa +17 — hợp lý. (3) Số lượng mục tiêu của proc sibling (idx2, Thần Lực Kích Phát) khi trúng AoE: cố định 5 mục tiêu, giống mọi proc đặc biệt khác trong cùng hàm.",
      trangThai: "DA_SUA",
      ghiChu:
        "Field ThanNu_SatTinhNghiaKhi. Gán PlayersBes.cs:8490. Proc riêng: Players.cs 41946/41949/41953 (PvE), 45584/45587/45591 (PK). Bán kính PvE: NpcClass.cs 2049,2074,2104. ĐÃ SỬA 03/09: Players.cs:46916 trước đây dùng num2 = 5×(1.0+giá trị×100.0) làm số mục tiêu AoE (ở 80 điểm ra tới 85 mục tiêu, dọn sạch bãi quái đông), nay đổi thành num2 = 5 cố định giống 2 proc anh em cạnh đó (46906/46908).",
    },
    {
      index: 4,
      id: 454,
      ten: "Tẩy tủy dịch cân",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Tăng % MP tối đa, tối đa +80% ở 80 điểm. Cộng thẳng vào công thức CharacterMax_MP.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs:8493 gán vào field DÙNG CHUNG NhanVat_KhiCong_ThemVao_MP (field riêng ThanNu_TayTuyDichCan tồn tại trong khai báo nhưng KHÔNG BAO GIỜ được gán — mồ côi vô hại vì hiệu ứng thật đã chạy qua field chung). Tiêu thụ PlayersBes.cs:2126.",
    },
    {
      index: 5,
      id: 193,
      ten: "Khí trầm đan điền",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Chuyển 1 phần Phòng Ngự cơ bản thành cả HP lẫn Lực Phòng Ngự Võ Công cộng thêm, tối đa 40% mỗi bên. Field dùng chung (cũng Tử Hào idx6).",
      trangThai: "BINH_THUONG",
      ghiChu: "Field DonKhi_DanDien. Gán PlayersBes.cs:8496. Tiêu thụ PlayersBes.cs:8537-8543.",
    },
    {
      index: 6,
      id: 455,
      ten: "Hắc hoa mạn khai",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Không xác định được ý đồ thiết kế gốc — field chỉ được gán rồi reset, không có công thức tiêu thụ nào. Đầu tư điểm hoàn toàn vô nghĩa.",
      trangThai: "CHET_HOAN_TOAN",
      ghiChu: "Field ThanNu_HacHoaManKhai. Gán+reset PlayersBes.cs~8504. Không tự chế công thức, cần Admin xác nhận ý đồ gốc.",
    },
    {
      index: 7,
      id: 456,
      ten: "Diệu thủ hồi xuân",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cùng tên với khí công hồi máu của Đại Phu (có 3 nơi tiêu thụ thật) nhưng bản Thần Nữ chỉ gán+reset — không có công thức hồi máu nào. Nhiều khả năng là THIẾU SÓT khi copy khung khí công từ Đại Phu sang Thần Nữ, không phải cố ý.",
      trangThai: "CHET_HOAN_TOAN",
      ghiChu: "Field ThanNu_DieuThuHoiXuan. Gán+reset PlayersBes.cs~8512. So sánh field song sinh: DAIPHU_DieuThuHoiXuan (Players.cs~42451/42472/42495).",
    },
    {
      index: 8,
      id: 457,
      ten: "Trường công kích lực (Thần nữ)",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Hệ số nhân sát thương CHIÊU trực tiếp, không qua proc — luôn áp dụng, tối đa +120% dame chiêu ở 80 điểm. Một trong những nguồn sát thương nền lớn nhất của Thần Nữ, áp dụng đồng nhất PvE và PK.",
      trangThai: "BINH_THUONG",
      ghiChu: "Field ThanNu_TruongCongKichLuc. Gán PlayersBes.cs:8515. Players.cs:41939 (PvE), 45578 (PK).",
    },
    {
      index: 9,
      id: 458,
      ten: "Hắc hoa tập trung",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa:
        "Khí công lõi 'combo debuff' của Thần Nữ, dùng chung 1 field cho hàng chục nhánh trạng thái bất thường (mỗi nhánh ứng 1 chiêu riêng nhưng roll trên cùng field này). Bao gồm: giảm giáp + giảm sát thương địch; giảm hiệu quả TẤT CẢ khí công có roll xác suất của địch (Giam_Tac_dung_Cua_Khi_Cong); 'loạn chiêu'; cơ chế 'BOM' (tích luỹ sát thương đòn tay 8 giây rồi nổ AoE tối đa 5 người bán kính ~100 KHÔNG lọc phe, cộng thêm phát riêng gây 30% Max HP vô điều kiện); DOT định kỳ; cờ miễn nhiễm tạm thời; tự buff cho Thần Nữ bằng nửa mức debuff vừa áp. ĐÃ SỬA (02/09): công thức nhân hệ số x5.0/x3.0 so với roll tại 9 vị trí khiến chỉ cần ~40-50% điểm đầu tư đã luôn-trúng — đã bọc Math.Min(...,99.0) khôi phục tính random.",
      trangThai: "DA_SUA",
      ghiChu:
        "Field ThanNu_HacHoaTapTrung. Gán+log VET PlayersBes.cs:8518-8525 ([VET_THANNU_HHTT]). 9 vị trí đã vá: Players.cs~43809-44287. Dame vô điều kiện 30% HP: Players.cs:1238-1251. AoE bom: Players.cs:78036-78078 (tối đa 5 người, bán kính 100). Kích hoạt phụ 611 (Cổ Độc Giải Trừ) mỗi lần cast bất kỳ chiêu nào trong họ này.",
    },
    {
      index: 10,
      id: 459,
      ten: "Chân vũ tuyệt kích (Thần nữ)",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 1.3,
      batBuocThangThien: null,
      moTa: "Proc dame chuẩn: trúng thì nhân dame ×1.3 cố định (hard-code, không đọc DB động — vô hại vì đúng số nhưng không linh hoạt nếu sau này đổi hệ số DB). Có buff tạm +10/-10 chồng lên nền gốc từ 1 chiêu khác.",
      trangThai: "BINH_THUONG",
      ghiChu: "Field ThanNu_ChanVu_TuyetKich. Gán PlayersBes.cs:8528. Proc: Players.cs:41955 (PvE), 45593 (PK). Buff tạm: Players.cs:42800-42804.",
    },
    {
      index: 11,
      id: 460,
      ten: "Vạn độc bất xâm",
      loai: "goc",
      heSo1: 1.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Kháng/miễn 1 hiệu ứng của địch. Trần thực tế 120 vs roll RNG.Next(1,110) — ĐÃ SỬA: bọc Math.Min(giá trị,110.0), từ ~73/80 điểm trở lên không còn tự động luôn-đúng nữa.",
      trangThai: "DA_SUA",
      ghiChu: "Field ThanNu_VanDocBatXam. Gán PlayersBes.cs:8531. Tiêu thụ + vá: Players.cs~42476.",
    },
    {
      index: null,
      id: 582,
      ten: "Khí công bí cấp (Thăng Thiên 6 thức - Thần Nữ)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 11,
      moTa: "Không có nơi nào đọc field ngoài gán giá trị — khác các field 'Thăng Thiên 6' của nghề khác (đều cộng vào HP/Phòng Ngự), field riêng bậc cao nhất của Thần Nữ bị bỏ trống hoàn toàn.",
      trangThai: "CHET_HOAN_TOAN",
      ghiChu: "Field ChongLaiThanPhap (KHÔNG có tiền tố ThanNu_). Gán duy nhất PlayersBes.cs:8907-8908. Không có consumer.",
    },
    {
      index: null,
      id: 610,
      ten: "Khí công bí tịch (Thăng Thiên 1 thức - Phẫn nộ điều tiết)",
      loai: "thang_thien",
      heSo1: 0.3,
      heSo2: null,
      batBuocThangThien: 6,
      moTa:
        "Khi tấn công (chiêu PK) 1 mục tiêu đang Nộ Khí, roll trúng thì CƯỠNG CHẾ kết thúc ngay trạng thái Nộ Khí của địch (huỷ buff sớm).",
      trangThai: "DA_SUA",
      ghiChu:
        "Field ThanNu_PhanNoDieuTiet. Gán PlayersBes.cs:8820-8822. ĐÃ SỬA 03/09: xoá khối if trùng lặp copy-paste tại Players.cs (roll 2 lần liên tiếp trong cùng 1 đòn khiến xác suất proc thật gần gấp đôi thiết kế), giờ chỉ còn 1 lần roll. Chỉ áp dụng chiêu PK, không có bản PvE.",
    },
    {
      index: null,
      id: 611,
      ten: "Khí công bí tịch (Thăng Thiên 2 thức - Cổ độc giải trừ)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 7,
      moTa: "Proc gỡ buff của địch: roll trúng thì cưỡng chế kết thúc sớm (dispel) TẤT CẢ buff của địch nằm trong danh sách cấu hình Gsconfig (~22 ID). Là hiệu ứng phụ độc lập, gọi mỗi lần cast bất kỳ chiêu nào trong họ Hắc Hoa Tập Trung (idx9).",
      trangThai: "BINH_THUONG",
      ghiChu:
        "Field ThanNu_CoDocGiaiTru. Gán PlayersBes.cs:8823-8825. Hàm: Players.cs:46041-46060, gọi tại 12 điểm trong họ chiêu idx9. Danh sách buff dispel: World.cs:100,3556,6198.",
    },
    {
      index: null,
      id: 612,
      ten: "Khí công bí tịch (Thăng Thiên 3 thức - Thần lực bảo hộ)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 8,
      moTa: "Passive cộng thêm Lực Phòng Ngự Võ Công, PIGGYBACK trên các chiêu khác (cleanse bản thân/cả đội, hoặc chiêu AoE tự buff). Khi 1 trong các chiêu đó proc thành công, cộng field vào ULPT trong 60 giây.",
      trangThai: "BINH_THUONG",
      ghiChu: "Field ThanNu_ThanLucBaoHo. Gán PlayersBes.cs:8826-8828. 3 nơi cộng buff: Players.cs:42509-42522, 43945-43970, 43987-44018. Tiêu thụ thật: PlayersBes.cs:2148.",
    },
    {
      index: null,
      id: 613,
      ten: "Khí công bí tịch (Thăng Thiên 4 thức - Mãn nguyệt cuồng phong)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Buff hỗ trợ đồng đội, chỉ hoạt động khi có team: roll trúng thì cấp Nộ Khí cho toàn đội trong phạm vi 300, 3 giây. Field dùng chung với nhiều nghề khác.",
      trangThai: "BINH_THUONG",
      ghiChu: "Field ThangThien_4_ManNguyetCuongPhong (chung). Gán PlayersBes.cs:8829-8831 (còn 4 case khác). Tiêu thụ Players.cs:46389-46420.",
    },
    {
      index: null,
      id: 614,
      ten: "Khí công bí tịch (Thăng Thiên 4 thức - Vọng mai thiêm hoa)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Cổng proc cho chiêu tự-buff 'Liệt Nhật Viêm Viêm': trúng thì gỡ 2 debuff đang mang, cấp +1000 Max HP tạm thời 3 giây, cộng thêm 60s ULPT nếu đã đầu Thăng Thiên 612.",
      trangThai: "BINH_THUONG",
      ghiChu: "Field ThangThien_4_VongMaiThiemHoa (chung). Gán PlayersBes.cs:8832-8834. Players.cs:42493-42523, 46250.",
    },
    {
      index: null,
      id: 616,
      ten: "Khí công bí tịch (Thăng Thiên 5 thức - Thi độc bạo phát)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 19,
      moTa:
        "Khí công CAPSTONE (bậc yêu cầu 19 — cao nhất trong toàn bộ khí công job13) cho cơ chế 'BOM' của idx9 (Hắc Hoa Tập Trung, state 44). Khi quả bom hết giờ (8s) và có sát thương đòn tay tích luỹ, sát thương AoE cuối cùng = sát thương tích luỹ × field — hệ số 0.1 khá nhỏ nhưng nhân vào giá trị TÍCH LUỸ (có thể rất lớn nếu bị nhiều người đánh dồn dập trong 8s) nên tác động thực tế lớn hơn con số cho thấy.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "Field ThanNu_ThiDocBaoPhat (RIÊNG, không dùng chung nghề nào khác). Gán PlayersBes.cs:8850-8852. Tiêu thụ: X_Than_Nu_Di_Thuong_Trang_Thai_Loai.cs:230-236 → Players.cs:78036-78078.",
    },
  ],
};
