import type { NgheData } from "./types";

export const JOB_11_MAI_LIEU_CHAN: NgheData = {
  job: 11,
  tenNghe: "Mai Liễu Chân",
  khiCong: [
    {
      index: 0,
      id: 650,
      ten: "Chưởng lực kích hoạt",
      loai: "goc",
      heSo1: 2.0,
      heSo2: 1.0,
      batBuocThangThien: null,
      moTa:
        "Khiên nội lực: khi bị tấn công (mọi đường), % sát thương tới được hấp thụ bằng Chưởng Lực (AP, hồ tài nguyên riêng job11, không phụ thuộc điểm khí công này). PK: AP tiêu = sát thương gốc × (field×1%). PvE (quái đánh người): dùng công thức riêng, CÓ trần 90%. ĐÃ SỬA (02/09): công thức GỐC thiếu nhân hệ số DB — chỉ cộng thẳng điểm thô, khiến trần thực tế bị khoá ở 85 thay vì thiết kế 165, chỉnh hệ số DB vô tác dụng.",
      trangThai: "DA_SUA",
      ghiChu:
        "Bug thiếu nhân hệ số: ĐÃ SỬA trước — PlayersBes.cs:8351. ĐÃ SỬA THÊM 03/09 (Admin xác nhận, nghề yếu nhất K/D=0.059 nhưng chấp nhận đổi cân bằng): 6 vị trí PK (Players.cs, gần ~39702/39743/40762/44904/45627/46072) trước đây dùng thẳng field×1% làm tỉ lệ hấp thụ không trần — ở mức đầu tối đa (165) ra 165% tức hấp thụ toàn bộ mỗi đòn miễn còn AP. Đã bọc Math.Min(MaiLieuChanBarrierPolicy.MaximumPveAbsorptionRate, ...) ở cả 6 vị trí, khớp đúng trần 90% mà nhánh PvE đã có sẵn.",
    },
    {
      index: 1,
      id: 651,
      ten: "Chưởng lực vận dụng",
      loai: "goc",
      heSo1: 2.0,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Tốc độ hồi Chưởng Lực (AP) theo thời gian. Cũng làm tham số cường độ buff trạng thái Phẫn Nộ.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8354. Players.cs:50309 (hồi AP mỗi tick), 69602 (tham số buff Phẫn Nộ).",
    },
    {
      index: 2,
      id: 653,
      ten: "Bách biến thần hành",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Né tránh %, ghi vào field dùng chung toàn hệ thống né tránh.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8357.",
    },
    {
      index: 3,
      id: 654,
      ten: "Huyền vũ thần công",
      loai: "goc",
      heSo1: 3000.0,
      heSo2: 0.2,
      batBuocThangThien: null,
      moTa: "THỜI LƯỢNG trạng thái 'Phẫn Nộ' — tối đa kéo dài ~250 giây. Khi ở Phẫn Nộ: cố định +20% Tấn Công và +20% giới hạn Chưởng Lực tối đa.",
      trangThai: "CON_LOI_CHUA_SUA",
      ghiChu:
        "PlayersBes.cs:8360. Tiêu thụ heSo1: Players.cs:69601. heSo2 (0.2) KHÔNG tìm thấy nơi tiêu thụ — có thể là hệ số dự phòng chưa nối mạch, mức ảnh hưởng THẤP vì khí công vẫn hoạt động đầy đủ qua heSo1.",
    },
    {
      index: 4,
      id: 656,
      ten: "Huyền vũ đích chỉ điểm",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.01,
      batBuocThangThien: null,
      moTa: "2 công dụng: mở rộng phạm vi tấn công (bán kính +48 tối đa), và cộng sức tấn công (+40% chỉ số công cao nhất).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8363-8364. Players.cs 38919,39531,42272,44459,44675.",
    },
    {
      index: 5,
      id: 657,
      ten: "Huyền vũ cường kích",
      loai: "goc",
      heSo1: 0.2,
      heSo2: 0.01,
      batBuocThangThien: null,
      moTa: "'Chí mạng' của Mai Liễu Chân trên đòn CHIÊU: lưu điểm thô, nhân hệ số ở nơi tiêu thụ — tỉ lệ proc dùng hệ số 1, sát thương khi trúng dùng hệ số 2. Thiết kế hợp lệ.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8367 (lưu thô). Players.cs:41868-41871 (PvE chiêu), 45509-45512 (PK chiêu).",
    },
    {
      index: 6,
      id: 191,
      ten: "Khí trầm đan điền",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cơ chế dùng chung nhiều nghề — cộng HP tối đa và phòng ngự võ công.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8370; tiêu thụ chung PlayersBes.cs:8537-8542.",
    },
    {
      index: 7,
      id: 658,
      ten: "Huyền vũ nguy hóa",
      loai: "goc",
      heSo1: 0.06,
      heSo2: 0.015,
      batBuocThangThien: null,
      moTa: "Tăng % sát thương chiêu nội tại (chỉ cần field>0, không cần proc). ĐÃ SỬA TRƯỚC ĐỢT AUDIT NÀY (25/08, không thuộc 27 bug 02/09): đường PvP từng gọi thẳng hệ số của 1 điểm thay vì dùng field đã tính sẵn (=điểm×hệ số) — hiệu ứng PvP trước đây chỉ ra ~1.5% thay vì đúng thiết kế ~120%. Đã sửa khớp PvE.",
      trangThai: "DA_SUA",
      ghiChu: "Đã sửa 25/08/2026. PlayersBes.cs:8373. Players.cs ~44643-44650 (PvP), ~41157-41159 (PvE).",
    },
    {
      index: 8,
      id: 659,
      ten: "Chưởng lực khôi phục",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 1.2,
      batBuocThangThien: null,
      moTa: "Proc HỒI ĐẦY Chưởng Lực (AP) khi bị tấn công lúc AP dưới nửa max. Đối xứng 3 vị trí (PK tay, PK chiêu, PvE).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8376. Players.cs:40456,45751; NpcClass.cs:1711.",
    },
    {
      index: 9,
      id: 660,
      ten: "Tật đố đích hóa thân",
      loai: "goc",
      heSo1: 1.0,
      heSo2: 0.1,
      batBuocThangThien: null,
      moTa:
        "Khắc chế 2 chiều với 2 nghề cụ thể (không phải giảm giáp chung). Chiều tấn công (đánh Kiếm/Đàm Hoa Liên): sát thương +10% cố định. Chiều phòng thủ (bị Đao/HanBaoQuan đánh): giảm sát thương nhận 5% cố định. Chỉ hoạt động trong PK, không có PvE.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8379. Players.cs 39915,40450,45504,45745.",
    },
    {
      index: 10,
      id: 661,
      ten: "Phẫn nộ bạo phát",
      loai: "goc",
      heSo1: 0.01,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Cơ chế 2 giai đoạn: tích điểm Nộ Khí (tỉ lệ cố định 40%, không đọc field, không scale theo điểm) rồi bùng nổ khi đủ 3 điểm (chỉ chiêu, đọc đúng field, nhân sát thương tối đa +80%). Thiết kế 2 tầng hợp lệ.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8382. Tích điểm: Players.cs 40461,45756; NpcClass.cs 1716. Bùng nổ: Players.cs 41164,44655.",
    },
    {
      index: 11,
      id: 318,
      ten: "Hấp huyết tiến kích",
      loai: "goc",
      heSo1: 0.5,
      heSo2: 0.0,
      batBuocThangThien: null,
      moTa: "Hồi máu khi bị đánh lúc HP dưới 50%. CHỈ tìm thấy 2 vị trí, cả hai đều PK — không có đường PvE, nhiều khả năng là chủ ý (kỹ năng phòng thủ PK).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8385. Players.cs:40465,45760.",
    },
    {
      index: null,
      id: 315,
      ten: "Thăng thiên 3 sát nhân quỷ",
      loai: "thang_thien",
      heSo1: 0.004,
      heSo2: null,
      batBuocThangThien: 8,
      moTa: "Sát thương chiêu PK tăng theo SỐ ĐỊCH gần đó (tối đa 5), đếm khác nhau theo bản đồ (TLC/Môn Chiến/thường). Kỹ năng AoE/hỗn chiến, hợp bối cảnh TLC.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8668-8669. Players.cs:44663-44715.",
    },
    {
      index: null,
      id: 316,
      ten: "Thăng thiên 1 huyền vũ lôi điện",
      loai: "thang_thien",
      heSo1: 2.0,
      heSo2: null,
      batBuocThangThien: 6,
      moTa: "Proc +40% sát thương cố định trên cả đòn tay và chiêu (PK lẫn PvE), roll trực tiếp theo % proc (điểm×2.0).",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8671-8672. Players.cs 39320,39920,41873,45514 — 4 vị trí đối xứng.",
    },
    {
      index: null,
      id: 325,
      ten: "Thăng thiên 2 huyền vũ trớ chú",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 7,
      moTa: "Proc cộng thẳng sát thương bằng 20% HP tối đa của người tấn công. Loại trừ với idx316 (else if) — 2 khí công Thăng Thiên 1 và 2 loại trừ nhau trên cùng 1 đòn.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8693-8694. Players.cs 39325,39925,41878,45519.",
    },
    {
      index: null,
      id: 326,
      ten: "Thăng thiên 4 liệt nhật viêm viêm",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa:
        "Ultimate Thăng Thiên 4 (Level>=140, Thăng Thiên>=9): giảm 15% phòng ngự mục tiêu 3 giây. ĐÁNG LƯU Ý CHO BÀN CÂN BẰNG: đây thực sự LÀ 1 cơ chế giảm giáp mục tiêu — không mâu thuẫn với 'khí công gốc của MLC không có giảm giáp' đã ghi ở audit trước, vì đây là ultimate hiếm/bậc cao, hiệu lực ngắn, cần trúng proc, không phải nguồn giảm giáp ổn định.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8696-8697 (field chung với case344/353/613). Players.cs:46084-46093.",
    },
    {
      index: null,
      id: 327,
      ten: "Thăng thiên 4 mãn nguyệt cuồng phong",
      loai: "thang_thien",
      heSo1: 0.5,
      heSo2: null,
      batBuocThangThien: 9,
      moTa: "Buff tổ đội khi bật Phẫn Nộ: +20% Tấn Công, +20% Phòng Ngự cho toàn đội trong phạm vi 300, 3 giây.",
      trangThai: "BINH_THUONG",
      ghiChu: "PlayersBes.cs:8699-8700. Players.cs:46389-46428 (yêu cầu TeamID!=0).",
    },
    {
      index: null,
      id: 580,
      ten: "Khí công bí cấp (Thăng Thiên 6 thức - Diệu Yến)",
      loai: "thang_thien",
      heSo1: 0.1,
      heSo2: null,
      batBuocThangThien: 11,
      moTa: "KHÔNG XÁC ĐỊNH được hiệu ứng gameplay — khí công CHẾT HOÀN TOÀN. Yêu cầu bậc Thăng Thiên 11, cực khó lên tới, nhưng đầu bao nhiêu điểm cũng không có tác dụng.",
      trangThai: "CON_LOI_CHUA_SUA",
      ghiChu:
        "PHÁT HIỆN MỚI 09/2026. PlayersBes.cs:8901-8902 (gán), 6434 (reset). Grep toàn repo cho 'BienNguyThanhAn': chỉ 3 kết quả (khai báo, reset, gán) — không có nơi đọc. Không có công thức gốc nào để suy luận ý đồ thiết kế thật.",
    },
    {
      index: null,
      id: 689,
      ten: "[Mai liễu chân] Khí công bí cấp thư (Ma hồn chi lực, Thăng Thiên 5 thức)",
      loai: "thang_thien",
      heSo1: 2.0,
      heSo2: null,
      batBuocThangThien: 10,
      moTa:
        "Ultimate riêng, KHÔNG dùng chung field. Khí công PHÒNG THỦ CHỐNG QUÁI (PvE thuần) — cộng thẳng vào tổng phòng ngự khi tính sát thương quái đánh người, KHÔNG có hiệu lực trong PK.",
      trangThai: "BINH_THUONG",
      ghiChu:
        "PlayersBes.cs:8790-8791. NpcClass.cs 1310+1415 (phòng ngự chống quái). ĐÁNG LƯU Ý cho bàn cân bằng: 1 trong 8 khí công Thăng Thiên của nghề yếu nhất PK (K/D=0.059) nhưng hoàn toàn không giúp gì cho PK — chỉ tăng khả năng sống sót khi luyện quái.",
    },
  ],
};
